"""Localized copy for the interactive automation experience.

Business credentials and the long-form FAQs stay in inhalt_*.py.
Demo examples are fictional and savings are explicitly estimates.
"""

COPY = {
    'de': {
        'title': 'Kastriot Tafolli · AI Automation, die Freiraum schafft',
        'description': 'AI Automation as a Service: individuelle KI-Workflows, Integration und laufende Betreuung von Kastriot Tafolli. Für Hotellerie, Gastronomie und Unternehmen.',
        'nav': ['Automation', 'Leistungen', 'Über mich', 'Kontakt'],
        'talk': 'Projekt besprechen', 'menu': 'Menü', 'motion': 'Bewegung',
        'status': 'OFFEN FÜR NEUE PROJEKTE', 'location': 'RÜGEN × SCHLUCHSEE',
        'hero': ['WENIGER', 'ROUTINE.', 'Mehr möglich.'],
        'hero_text': 'Ich baue KI-Systeme, die Arbeit übernehmen. Damit Ihr Team wieder Zeit für das hat, was Menschen am besten können.',
        'hero_cta': 'Entdecken Sie Automation', 'hero_link': 'Lernen wir uns kennen',
        'art_label': 'MENSCHLICHE IDEEN. INTELLIGENTE SYSTEME.',
        'scroll': 'SCROLLEN & ENTDECKEN', 'intro': 'TECHNOLOGIE MIT GESPÜR FÜR MENSCHEN',
        'manifesto': ['Ihr nächster', 'Mitarbeiter', 'ist ein System.'],
        'manifesto_text': 'Eine Anfrage um 23:48 Uhr. Eine Rechnung, die niemand abtippen möchte. Ein Bericht, der morgens fertig sein sollte. Genau da beginnt gute Automatisierung.',
        'manifesto_small': 'Sie geben die Richtung vor. Ich verbinde Ihre Abläufe, Ihre Systeme und KI zu etwas, das im Alltag wirklich hilft.',
        'service_label': 'DAS ANGEBOT', 'service_title': ['AI Automation', 'as a Service.'],
        'service_text': 'Für Ihr Unternehmen gebaut. In Ihre bestehenden Systeme integriert. Von mir laufend betreut. Vom ersten Workflow bis zum nächsten Schritt.',
        'service_tags': ['Individuelle Workflows', 'Menschliche Kontrolle', 'Laufende Betreuung'],
        'lab_label': '01 / AUTOMATION ZUM AUSPROBIEREN', 'lab_title': ['Keine Blackbox.', 'Ein Aha-Moment.'],
        'lab_text': 'Wählen Sie einen Ablauf und schicken Sie ihn durch die Demo. So wird aus einer kleinen Routine ein intelligenter Workflow.',
        'demo_label': 'INTERAKTIVE DEMO · FIKTIVE BEISPIELDATEN',
        'scenarios': ['Gästeanfrage', 'Rechnung', 'E-Mail'],
        'stages': ['Eingang', 'Verstehen', 'Handeln', 'Prüfen', 'Ergebnis'],
        'stage_notes': [
            'Eine neue Anfrage kommt an. Ihr Team muss noch nichts tun.',
            'Die KI erkennt Absicht, Sprache und wichtige Informationen.',
            'Der Workflow bereitet die passende Aktion in Ihrem System vor.',
            'Regeln prüfen das Ergebnis. Unklare Fälle gehen an Ihr Team.',
            'Der Vorgang ist vorbereitet, dokumentiert und bereit zur Freigabe.'
        ],
        'incoming': 'EINGANG', 'outgoing': 'ERGEBNIS', 'ready': 'Bereit für einen Testlauf',
        'run': 'Workflow starten', 'running': 'Workflow läuft', 'replay': 'Noch einmal abspielen',
        'demo_hint': 'Eine Simulation zur Erklärung. Es werden keine Nachrichten versendet oder Buchungen vorgenommen.',
        'demos': [
            {'source': 'GÄSTEANFRAGE / 23:48', 'subject': 'Ein Wochenende am Meer?', 'message': 'Guten Abend! Haben Sie vom 16.–18. Oktober ein Doppelzimmer? Wir reisen mit unserem Hund. Gibt es Frühstück?', 'fields': ['Absicht: Zimmeranfrage', 'Aufenthalt: 16.–18. Oktober', 'Wunsch: Hund + Frühstück'], 'result_title': 'Persönliche Antwort vorbereitet.', 'result': 'Zimmerwunsch und Zusatzfragen erkannt. Verfügbarkeit und Haustierregeln zur Prüfung an die Rezeption übergeben. Antwortentwurf liegt bereit.', 'receipt': 'ANFRAGE STRUKTURIERT · FREIGABE DURCH REZEPTION'},
            {'source': 'BUCHHALTUNG / 09:12', 'subject': 'Eine Rechnung. Kein Abtippen.', 'message': 'Rechnung #2026-1042 · Musterlieferant GmbH · 840,00 € netto + 159,60 € USt. · Gesamt: 999,60 € · Fällig: 30. Oktober.', 'fields': ['Beleg: Rechnung #2026-1042', 'Gesamtbetrag: 999,60 €', 'Fälligkeit: 30. Oktober'], 'result_title': 'Beleg erfasst. Zahlen geprüft.', 'result': 'Lieferant, Positionen und Beträge ausgelesen. Nettobetrag und Umsatzsteuer abgeglichen. Buchungsvorschlag zur Freigabe vorbereitet.', 'receipt': 'BELEG STRUKTURIERT · FREIGABE DURCH BUCHHALTUNG'},
            {'source': 'POSTEINGANG / 14:06', 'subject': 'Die richtige Nachricht. Beim richtigen Team.', 'message': 'Hallo, wir planen ein Firmenevent mit 40 Personen. Könnten Sie uns ein Angebot für einen Abend mit Dinner und Getränken schicken?', 'fields': ['Absicht: Veranstaltungsanfrage', 'Teilnehmende: 40 Personen', 'Ziel: Event-Team'], 'result_title': 'Anfrage sortiert. Team informiert.', 'result': 'Event-Anfrage erkannt und dem richtigen Team zugeordnet. Fehlende Angaben markiert. Rückfrage zu Datum und Budget als Entwurf vorbereitet.', 'receipt': 'ANFRAGE ZUGEORDNET · ANTWORTENTWURF BEREIT'}
        ],
        'care_label': '02 / MEHR ALS EIN EINMALIGES SETUP', 'care_title': ['Läuft.', 'Und wird besser.'],
        'care_text': 'Automation as a Service heißt: Ich begleite Ihr System auch nach dem Start. Wenn sich Ihr Betrieb verändert, entwickelt sich Ihr Workflow mit.',
        'care_items': [('Verbinden', 'Ihre Tools bleiben. Ich baue die Verbindung zwischen Posteingang, Dokumenten, Reservierung und Team.'), ('Betreuen', 'Antworten prüfen, Fehler erkennen, Kosten beobachten und bei Bedarf eingreifen.'), ('Weiterentwickeln', 'Neue Abläufe ergänzen, Regeln anpassen und aus echten Rückmeldungen lernen.')],
        'care_note': 'IHR TEAM BEHÄLT DAS LETZTE WORT.', 'care_orbit': ['TOOLS', 'KI', 'TEAM', 'BETREUUNG'],
        'roi_label': '03 / IHR POTENZIAL', 'roi_title': ['Zeit ist wertvoll.', 'Holen Sie sie zurück.'],
        'roi_text': 'Was könnte ein automatisierter Ablauf freimachen? Verändern Sie die Werte und entdecken Sie eine mögliche Größenordnung.',
        'roi_labels': ['Vorgänge pro Arbeitstag', 'Minuten pro Vorgang', 'Interner Stundensatz', 'Automatisierbarer Anteil'],
        'roi_units': ['Vorgänge', 'Min.', '€', '%'], 'hours': 'Stunden / Monat', 'value': 'Rechnerischer Zeitwert / Monat',
        'roi_note': 'Modellrechnung mit 22 Arbeitstagen pro Monat. Zeitwert vor Servicekosten, keine garantierte Einsparung. Der tatsächliche Anteil hängt vom Workflow ab.',
        'roi_cta': 'Mein Potenzial besprechen',
        'services_label': '04 / WAS ICH NOCH BEWEGE', 'services_title': ['Eine Perspektive.', 'Viele Möglichkeiten.'],
        'services': [('01', 'AI & AUTOMATION', 'Ein System, das mitarbeitet.', 'Individuelle KI-Workflows, laufende Betreuung und TeamO als digitaler Mitarbeiter.', 'ki-automatisierung.html', 'Automation ansehen'), ('02', 'F&B-BERATUNG', 'Bessere Abläufe. Bessere Zahlen.', 'Operative Erfahrung für Einkauf, Wareneinsatz, Verträge und Führung in Ihrem Haus.', 'fb-beratung.html', 'F&B entdecken'), ('03', 'DIGITAL & WEB', 'Ein Auftritt, der etwas bewegt.', 'Websites, Sichtbarkeit und Online-Marketing mit einem klaren Ziel: mehr direkte Anfragen.', 'online-marketing.html', 'Digital entdecken')],
        'about_label': '05 / DER MENSCH HINTER DEN SYSTEMEN', 'about_title': ['Ich kenne den Alltag.', 'Und den Code.'],
        'about_text': 'Ich bin Kastriot Tafolli. Über 15 Jahre Führung in der 5-Sterne-Hotellerie haben mir gezeigt, wo Zeit verloren geht. Als Softwareingenieur mit Schwerpunkt KI baue ich die Systeme, die genau dort ansetzen.',
        'about_link': 'Mehr über mich', 'about_caption': 'KASTRIOT TAFOLLI / TB SOLUTIONS',
        'credentials': [('15+', 'Jahre 5-Sterne-Hotellerie'), ('200+', 'Mitarbeitende gleichzeitig geführt'), ('50+', 'Nachwuchskräfte ausgebildet')],
        'experience_label': 'BERUFLICHE STATIONEN',
        'process_label': '06 / VON DER IDEE IN DEN ALLTAG', 'process_title': ['Groß denken.', 'Konkret anfangen.'],
        'process': [('Zuhören.', 'Wir sprechen über Ihren Betrieb, Ihre Engpässe und den Ablauf, der wirklich Zeit kostet.'), ('Bauen.', 'Ein klar begrenzter erster Workflow. Mit Ihren Tools, Ihren Regeln und Tests mit Ihrem Team.'), ('Begleiten.', 'Nach dem Start beobachte ich die Ergebnisse und entwickle das System mit Ihnen weiter.')],
        'faq_label': '07 / GUTE FRAGEN', 'faq_title': 'Noch etwas offen?',
        'cta_label': 'DER NÄCHSTE SCHRITT IST EIN GESPRÄCH.', 'cta_title': ['Was wäre, wenn', 'das einfach', 'laufen würde?'],
        'cta_text': 'Erzählen Sie mir von einem Ablauf, der Sie Zeit kostet. Wir finden heraus, was möglich ist.',
        'cta_button': 'Lassen Sie uns sprechen', 'cta_note': '30 MINUTEN. UNVERBINDLICH. MENSCH ZU MENSCH.',
        'footer_tag': 'MENSCHLICH DENKEN. INTELLIGENT HANDELN.', 'top': 'Zurück nach oben',
        'detail_hero': ['INTELLIGENTE', 'ABLÄUFE.', 'Mehr Freiraum.'],
        'story_label': 'VOM DURCHEINANDER ZUM ZUSAMMENSPIEL',
        'story_titles': ['Zu viele Handgriffe.', 'Ein verbundenes System.', 'Mehr Zeit für Menschen.'],
        'story_copies': ['Posteingang, Belege, Anrufe. Jede kleine Aufgabe zieht Aufmerksamkeit vom Wesentlichen ab.', 'Ihre Informationen finden ihren Weg. Die KI strukturiert, Regeln prüfen, Ihr Team entscheidet.', 'Weniger hin und her. Mehr Raum für Gäste, Ideen und die Arbeit, die Sie voranbringt.'],
        'story_tasks': ['E-MAIL', 'RECHNUNG', 'ANRUF', 'BERICHT', 'ANFRAGE', 'DATEN'],
        'story_outcome': 'FREIRAUM',
    },
    'en': {
        'title': 'Kastriot Tafolli · AI automation that makes room for more',
        'description': 'AI Automation as a Service: custom AI workflows, integration and ongoing care by Kastriot Tafolli. For hospitality, restaurants and businesses.',
        'nav': ['Automation', 'Services', 'About me', 'Contact'], 'talk': 'Let’s talk', 'menu': 'Menu', 'motion': 'Motion',
        'status': 'OPEN FOR NEW PROJECTS', 'location': 'RÜGEN × SCHLUCHSEE',
        'hero': ['LESS', 'ROUTINE.', 'More possible.'],
        'hero_text': 'I build AI systems that take work off your hands. So your team can get back to what people do best.',
        'hero_cta': 'Discover automation', 'hero_link': 'Let’s get to know each other', 'art_label': 'HUMAN IDEAS. INTELLIGENT SYSTEMS.',
        'scroll': 'SCROLL TO DISCOVER', 'intro': 'TECHNOLOGY WITH A FEEL FOR PEOPLE',
        'manifesto': ['Your next', 'team member', 'is a system.'],
        'manifesto_text': 'An enquiry at 11:48 pm. An invoice nobody wants to type up. A report that should be ready in the morning. That’s where good automation begins.',
        'manifesto_small': 'You set the direction. I connect your processes, your tools and AI into something that makes everyday work easier.',
        'service_label': 'THE OFFER', 'service_title': ['AI Automation', 'as a Service.'],
        'service_text': 'Built for your business. Connected to your existing tools. Continuously managed by me. From the first workflow to the next opportunity.',
        'service_tags': ['Custom workflows', 'Human oversight', 'Ongoing care'],
        'lab_label': '01 / EXPERIENCE AUTOMATION', 'lab_title': ['No black box.', 'A lightbulb moment.'],
        'lab_text': 'Choose a process and run it through the demo. See an everyday task become an intelligent workflow.',
        'demo_label': 'INTERACTIVE DEMO · FICTIONAL SAMPLE DATA', 'scenarios': ['Guest enquiry', 'Invoice', 'Email'],
        'stages': ['Receive', 'Understand', 'Act', 'Check', 'Result'],
        'stage_notes': ['A new request arrives. Your team doesn’t need to act yet.', 'AI identifies intent, language and key information.', 'The workflow prepares the right action in your system.', 'Rules check the result. Unclear cases go to your team.', 'The request is structured, documented and ready for approval.'],
        'incoming': 'INPUT', 'outgoing': 'OUTPUT', 'ready': 'Ready for a test run', 'run': 'Run workflow', 'running': 'Workflow running', 'replay': 'Play again',
        'demo_hint': 'An explanatory simulation. No messages are sent and no bookings are made.',
        'demos': [
            {'source': 'GUEST ENQUIRY / 23:48', 'subject': 'A weekend by the sea?', 'message': 'Good evening! Do you have a double room for 16–18 October? We’re travelling with our dog. Is breakfast available?', 'fields': ['Intent: room enquiry', 'Stay: 16–18 October', 'Request: dog + breakfast'], 'result_title': 'A personal response, prepared.', 'result': 'Room request and additional questions identified. Availability and pet policy passed to reception for checking. A response draft is ready.', 'receipt': 'REQUEST STRUCTURED · RECEPTION APPROVAL REQUIRED'},
            {'source': 'ACCOUNTING / 09:12', 'subject': 'An invoice. Without the typing.', 'message': 'Invoice #2026-1042 · Example Supplier Ltd. · €840.00 net + €159.60 VAT · Total: €999.60 · Due: 30 October.', 'fields': ['Document: invoice #2026-1042', 'Total: €999.60', 'Due: 30 October'], 'result_title': 'Captured. Numbers checked.', 'result': 'Supplier, items and amounts extracted. Net amount and VAT reconciled. An accounting entry is prepared for approval.', 'receipt': 'DOCUMENT STRUCTURED · ACCOUNTING APPROVAL REQUIRED'},
            {'source': 'INBOX / 14:06', 'subject': 'The right message. The right team.', 'message': 'Hello, we’re planning a company event for 40 people. Could you send us a quote for an evening with dinner and drinks?', 'fields': ['Intent: event enquiry', 'Guests: 40 people', 'Destination: events team'], 'result_title': 'Sorted. Team notified.', 'result': 'Event enquiry identified and assigned to the right team. Missing details highlighted. A question about date and budget is drafted.', 'receipt': 'REQUEST ASSIGNED · RESPONSE DRAFT READY'}
        ],
        'care_label': '02 / BEYOND THE INITIAL SETUP', 'care_title': ['It works.', 'And gets better.'],
        'care_text': 'Automation as a Service means I stay with your system after launch. As your business changes, your workflows evolve with it.',
        'care_items': [('Connect', 'Keep your tools. I connect your inbox, documents, reservations and team.'), ('Manage', 'Review responses, detect errors, monitor costs and step in when needed.'), ('Evolve', 'Add workflows, adapt rules and learn from real feedback.')],
        'care_note': 'YOUR TEAM HAS THE FINAL SAY.', 'care_orbit': ['TOOLS', 'AI', 'TEAM', 'CARE'],
        'roi_label': '03 / YOUR POTENTIAL', 'roi_title': ['Time is valuable.', 'Take it back.'],
        'roi_text': 'How much time could an automated process free up? Adjust the inputs to explore a possible outcome.',
        'roi_labels': ['Tasks per working day', 'Minutes per task', 'Internal hourly rate', 'Automatable share'],
        'roi_units': ['tasks', 'min.', '€', '%'], 'hours': 'hours / month', 'value': 'Estimated time value / month',
        'roi_note': 'Model based on 22 working days per month. Time value before service costs, not guaranteed savings. The actual share depends on the workflow.', 'roi_cta': 'Discuss my potential',
        'services_label': '04 / OTHER WAYS I HELP', 'services_title': ['One perspective.', 'Many possibilities.'],
        'services': [('01', 'AI & AUTOMATION', 'A system that works alongside you.', 'Custom AI workflows, ongoing care and TeamO as your digital colleague.', 'ki-automatisierung.html', 'Explore automation'), ('02', 'F&B CONSULTING', 'Better processes. Better numbers.', 'Hands-on expertise in purchasing, cost control, contracts and leadership.', 'fb-beratung.html', 'Explore F&B'), ('03', 'DIGITAL & WEB', 'A presence that makes a difference.', 'Websites, visibility and online marketing with one goal: more direct enquiries.', 'online-marketing.html', 'Explore digital')],
        'about_label': '05 / THE PERSON BEHIND THE SYSTEMS', 'about_title': ['I know the everyday.', 'And the code.'],
        'about_text': 'I’m Kastriot Tafolli. Over 15 years leading teams in five-star hospitality showed me where time gets lost. As a software engineer focused on AI, I build systems that solve those very problems.',
        'about_link': 'More about me', 'about_caption': 'KASTRIOT TAFOLLI / TB SOLUTIONS',
        'credentials': [('15+', 'years in five-star hospitality'), ('200+', 'employees led simultaneously'), ('50+', 'young professionals trained')], 'experience_label': 'CAREER STATIONS',
        'process_label': '06 / FROM IDEA TO EVERYDAY', 'process_title': ['Think big.', 'Start with something real.'],
        'process': [('Listen.', 'We discuss your business, your bottlenecks and the process that takes up your time.'), ('Build.', 'A focused first workflow. With your tools, your rules and tests with your team.'), ('Stay.', 'After launch, I monitor results and keep improving your system with you.')],
        'faq_label': '07 / GOOD QUESTIONS', 'faq_title': 'Anything else on your mind?',
        'cta_label': 'THE NEXT STEP IS A CONVERSATION.', 'cta_title': ['What if', 'it just', 'worked?'],
        'cta_text': 'Tell me about a process that takes up your time. Let’s find out what’s possible.',
        'cta_button': 'Let’s talk', 'cta_note': '30 MINUTES. NO OBLIGATION. HUMAN TO HUMAN.',
        'footer_tag': 'THINK HUMAN. ACT INTELLIGENT.', 'top': 'Back to top', 'detail_hero': ['INTELLIGENT', 'WORKFLOWS.', 'More freedom.'],
        'story_label': 'FROM SCATTERED TASKS TO CONNECTED WORK',
        'story_titles': ['Too many little tasks.', 'One connected system.', 'More time for people.'],
        'story_copies': ['Emails, invoices, phone calls. Each small task pulls your attention away from what matters.', 'Your information finds its way. AI structures it, rules check it, your team decides.', 'Less back and forth. More room for guests, ideas and work that moves you forward.'],
        'story_tasks': ['EMAIL', 'INVOICE', 'CALL', 'REPORT', 'ENQUIRY', 'DATA'], 'story_outcome': 'FREEDOM',
    },
    'sq': {
        'title': 'Kastriot Tafolli · Automatizim me AI për më shumë kohë',
        'description': 'AI Automation as a Service: procese të personalizuara me AI, integrim dhe mirëmbajtje nga Kastriot Tafolli. Për hotele, restorante dhe biznese.',
        'nav': ['Automatizimi', 'Shërbimet', 'Rreth meje', 'Kontakti'], 'talk': 'Të flasim', 'menu': 'Menu', 'motion': 'Lëvizja',
        'status': 'I HAPUR PËR PROJEKTE TË REJA', 'location': 'RÜGEN × SCHLUCHSEE',
        'hero': ['MË PAK', 'RUTINË.', 'Më shumë mundësi.'],
        'hero_text': 'Ndërtoj sisteme me AI që marrin përsipër punën. Që ekipi juaj të ketë kohë për atë që njerëzit bëjnë më mirë.',
        'hero_cta': 'Zbuloni automatizimin', 'hero_link': 'Të njihemi', 'art_label': 'IDE NJERËZORE. SISTEME INTELIGJENTE.',
        'scroll': 'LËVIZNI PËR TË ZBULUAR', 'intro': 'TEKNOLOGJI ME NDJESHMËRI PËR NJERËZIT',
        'manifesto': ['Anëtari juaj', 'i ardhshëm', 'është një sistem.'],
        'manifesto_text': 'Një kërkesë në 23:48. Një faturë që askush nuk dëshiron ta shkruajë. Një raport që duhet të jetë gati në mëngjes. Këtu fillon automatizimi i mirë.',
        'manifesto_small': 'Ju përcaktoni drejtimin. Unë lidh proceset, mjetet dhe AI-në për t’ju ndihmuar në punën e përditshme.',
        'service_label': 'OFERTA', 'service_title': ['AI Automation', 'as a Service.'],
        'service_text': 'Ndërtuar për biznesin tuaj. Integruar në sistemet ekzistuese. Mirëmbajtur vazhdimisht nga unë. Nga procesi i parë te mundësia e ardhshme.',
        'service_tags': ['Procese të personalizuara', 'Kontroll njerëzor', 'Mirëmbajtje e vazhdueshme'],
        'lab_label': '01 / PROVONI AUTOMATIZIMIN', 'lab_title': ['Pa mistere.', 'Gjithçka bëhet e qartë.'],
        'lab_text': 'Zgjidhni një proces dhe nisni demonstrimin. Shihni si një detyrë rutinë bëhet një proces inteligjent.',
        'demo_label': 'DEMONSTRIM INTERAKTIV · TË DHËNA FIKTIVE', 'scenarios': ['Kërkesë mysafiri', 'Faturë', 'Email'],
        'stages': ['Marrja', 'Kuptimi', 'Veprimi', 'Kontrolli', 'Rezultati'],
        'stage_notes': ['Mbërrin një kërkesë e re. Ekipi ende nuk ka nevojë të veprojë.', 'AI identifikon qëllimin, gjuhën dhe informacionin e rëndësishëm.', 'Procesi përgatit veprimin e duhur në sistemin tuaj.', 'Rregullat kontrollojnë rezultatin. Rastet e paqarta i kalojnë ekipit.', 'Kërkesa është e strukturuar, e dokumentuar dhe gati për miratim.'],
        'incoming': 'HYRJA', 'outgoing': 'REZULTATI', 'ready': 'Gati për provë', 'run': 'Nisni procesin', 'running': 'Procesi po punon', 'replay': 'Luajeni përsëri',
        'demo_hint': 'Një simulim shpjegues. Nuk dërgohen mesazhe dhe nuk bëhen rezervime.',
        'demos': [
            {'source': 'KËRKESË MYSAFIRI / 23:48', 'subject': 'Një fundjavë pranë detit?', 'message': 'Mirëmbrëma! A keni dhomë dyshe për 16–18 tetor? Udhëtojmë me qenin tonë. A ka mëngjes?', 'fields': ['Qëllimi: kërkesë dhome', 'Qëndrimi: 16–18 tetor', 'Dëshira: qen + mëngjes'], 'result_title': 'Përgjigje personale e përgatitur.', 'result': 'Kërkesa dhe pyetjet u identifikuan. Disponueshmëria dhe rregullat për kafshët i kalojnë recepsionit për kontroll. Drafti i përgjigjes është gati.', 'receipt': 'KËRKESË E STRUKTURUAR · MIRATIM NGA RECEPSIONI'},
            {'source': 'KONTABILITET / 09:12', 'subject': 'Një faturë. Pa shkrim manual.', 'message': 'Fatura #2026-1042 · Furnitori Shembull · 840,00 € neto + 159,60 € TVSH · Gjithsej: 999,60 € · Afati: 30 tetor.', 'fields': ['Dokumenti: fatura #2026-1042', 'Gjithsej: 999,60 €', 'Afati: 30 tetor'], 'result_title': 'Regjistruar. Shifrat u kontrolluan.', 'result': 'Furnitori, artikujt dhe shumat u nxorën. Shuma neto dhe TVSH u krahasuan. Regjistrimi kontabël është gati për miratim.', 'receipt': 'DOKUMENT I STRUKTURUAR · MIRATIM NGA KONTABILITETI'},
            {'source': 'POSTA / 14:06', 'subject': 'Mesazhi i duhur. Ekipi i duhur.', 'message': 'Përshëndetje, planifikojmë një event kompanie me 40 persona. Mund të na dërgoni ofertë për darkë dhe pije?', 'fields': ['Qëllimi: kërkesë eventi', 'Pjesëmarrës: 40 persona', 'Destinacioni: ekipi i eventeve'], 'result_title': 'Sistemuar. Ekipi u njoftua.', 'result': 'Kërkesa u identifikua dhe iu caktua ekipit të duhur. U shënuan të dhënat që mungojnë. U përgatit pyetja për datën dhe buxhetin.', 'receipt': 'KËRKESË E CAKTUAR · DRAFT PËRGJIGJEJE GATI'}
        ],
        'care_label': '02 / PËRTEJ INSTALIMIT FILLESTAR', 'care_title': ['Funksionon.', 'Dhe përmirësohet.'],
        'care_text': 'Automation as a Service do të thotë që e mbështes sistemin edhe pas nisjes. Ndërsa biznesi ndryshon, proceset zhvillohen me të.',
        'care_items': [('Lidhja', 'Mjetet tuaja mbeten. Lidh postën, dokumentet, rezervimet dhe ekipin.'), ('Mirëmbajtja', 'Kontrolloj përgjigjet, identifikoj gabimet, ndjek kostot dhe ndërhyj kur duhet.'), ('Zhvillimi', 'Shtoj procese, përshtat rregullat dhe mësoj nga reagimet reale.')],
        'care_note': 'EKIPI JUAJ KA FJALËN E FUNDIT.', 'care_orbit': ['MJETET', 'AI', 'EKIPI', 'KUJDESI'],
        'roi_label': '03 / POTENCIALI JUAJ', 'roi_title': ['Koha ka vlerë.', 'Rikthejeni.'],
        'roi_text': 'Sa kohë mund të lirojë një proces i automatizuar? Ndryshoni vlerat për të zbuluar një rezultat të mundshëm.',
        'roi_labels': ['Detyra për ditë pune', 'Minuta për detyrë', 'Kostoja e orës', 'Pjesa e automatizueshme'], 'roi_units': ['detyra', 'min.', '€', '%'],
        'hours': 'orë / muaj', 'value': 'Vlera e llogaritur e kohës / muaj',
        'roi_note': 'Model me 22 ditë pune në muaj. Vlera para kostove të shërbimit, jo kursim i garantuar. Pjesa reale varet nga procesi.', 'roi_cta': 'Të flasim për potencialin tim',
        'services_label': '04 / SHËRBIME TË TJERA', 'services_title': ['Një perspektivë.', 'Shumë mundësi.'],
        'services': [('01', 'AI & AUTOMATIZIM', 'Një sistem që punon me ju.', 'Procese me AI, mirëmbajtje dhe TeamO si koleg digjital.', 'ki-automatisierung.html', 'Zbuloni automatizimin'), ('02', 'KONSULENCË F&B', 'Procese më të mira. Shifra më të mira.', 'Përvojë në blerje, kontroll kostosh, kontrata dhe drejtim.', 'fb-beratung.html', 'Zbuloni F&B'), ('03', 'DIGJITAL & WEB', 'Një prezencë që sjell ndryshim.', 'Faqe web, dukshmëri dhe marketing me një synim: më shumë kërkesa direkte.', 'online-marketing.html', 'Zbuloni shërbimet digjitale')],
        'about_label': '05 / NJERIU PAS SISTEMEVE', 'about_title': ['Njoh përditshmërinë.', 'Dhe kodin.'],
        'about_text': 'Jam Kastriot Tafolli. Mbi 15 vjet drejtim në hoteleri me pesë yje më kanë treguar ku humbet koha. Si inxhinier softueri me fokus në AI, ndërtoj sisteme që zgjidhin këto probleme.', 'about_link': 'Më shumë rreth meje', 'about_caption': 'KASTRIOT TAFOLLI / TB SOLUTIONS',
        'credentials': [('15+', 'vjet hoteleri me pesë yje'), ('200+', 'punonjës të drejtuar njëkohësisht'), ('50+', 'profesionistë të rinj të trajnuar')], 'experience_label': 'ETAPAT PROFESIONALE',
        'process_label': '06 / NGA IDEJA NË PËRDITSHMËRI', 'process_title': ['Mendoni gjerë.', 'Filloni konkretisht.'],
        'process': [('Dëgjoj.', 'Flasim për biznesin, pengesat dhe procesin që ju merr kohë.'), ('Ndërtoj.', 'Një proces fillestar i kufizuar qartë. Me mjetet, rregullat dhe testet me ekipin tuaj.'), ('Mbështes.', 'Pas nisjes monitoroj rezultatet dhe zhvilloj sistemin bashkë me ju.')],
        'faq_label': '07 / PYETJE TË MIRA', 'faq_title': 'Diçka ende e paqartë?',
        'cta_label': 'HAPI TJETËR ËSHTË NJË BISEDE.', 'cta_title': ['Po sikur', 'thjesht të', 'funksiononte?'],
        'cta_text': 'Më tregoni një proces që ju merr kohë. Të zbulojmë çfarë është e mundur.', 'cta_button': 'Të flasim', 'cta_note': '30 MINUTA. PA DETYRIM. NJERI ME NJERI.',
        'footer_tag': 'MENDONI SI NJERI. VEPRONI ME INTELIGJENCË.', 'top': 'Kthehu lart', 'detail_hero': ['PROCESE', 'INTELIGJENTE.', 'Më shumë liri.'],
        'story_label': 'NGA DETYRAT E SHPËRNDARA TE PUNA E LIDHUR',
        'story_titles': ['Shumë detyra të vogla.', 'Një sistem i lidhur.', 'Më shumë kohë për njerëzit.'],
        'story_copies': ['Email, fatura, telefonata. Çdo detyrë e vogël largon vëmendjen nga ajo që ka rëndësi.', 'Informacioni gjen rrugën e vet. AI e strukturon, rregullat e kontrollojnë, ekipi vendos.', 'Më pak vajtje-ardhje. Më shumë hapësirë për mysafirë, ide dhe punë që ju çon përpara.'],
        'story_tasks': ['EMAIL', 'FATURË', 'TELEFON', 'RAPORT', 'KËRKESË', 'TË DHËNA'], 'story_outcome': 'LIRI',
    },
}

# The homepage introduces the whole portfolio; automation has a dedicated page.
POSITIONING={
'de':dict(title='Kastriot Tafolli · Hotellerie, Gastronomie, KI & Technologie',description='Hotellerie und Gastronomie treffen KI und Softwareentwicklung: Kastriot Tafolli verbindet F&B-Beratung, Einkauf, Digitalisierung und AI Automation as a Service.',nav=['Leistungen','Über mich','Wissen','Kontakt'],hero_text='Hotellerie. Gastronomie. KI. Technologie. Ich bin Kastriot Tafolli und verbinde operative Führung mit digitalem Handwerk – vom Restaurantalltag bis zum intelligenten System.',hero_cta='Mein Portfolio entdecken',manifesto=['Gastgeber.','Entwickler.','Ein Mensch.'],manifesto_text='Ich kenne den Service am Gast, die Verantwortung für Teams und die Zahlen hinter einem Betrieb. Und ich entwickle Software und KI. Diese seltene Verbindung macht meine Arbeit aus.',manifesto_small='F&B-Beratung, Lieferantenvereinbarungen und Kalkulation gehören für mich ebenso dazu wie Digitalisierung, Cybersecurity und intelligente Automatisierung. Ich verstehe den Betrieb und kann die passende Technik umsetzen.',services_label='DAS PORTFOLIO / PRAXIS × TECHNOLOGIE',services_title=['Viele Kompetenzen.','Eine Handschrift.'],portfolio_link='Alle 22 Leistungsbereiche entdecken',about_text='Ich bin Kastriot Tafolli. Vom klassischen Service über die Führung mehrerer Hotel-Outlets bis zu Softwareentwicklung und KI Engineering: Meine Erfahrung verbindet Menschen, Betrieb und Technologie. Ich berate nicht nur über Abläufe – ich kenne die Arbeit, die dahintersteckt.',cta_text='Ob F&B, Einkauf, Digitalisierung oder KI: Erzählen Sie mir, was Sie in Ihrem Betrieb bewegen möchten.'),
'en':dict(title='Kastriot Tafolli · Hospitality, gastronomy, AI & technology',description='Hospitality meets AI and software development. Kastriot Tafolli connects F&B consulting, purchasing, digital transformation and AI Automation as a Service.',nav=['Services','About me','Insights','Contact'],hero_text='Hospitality. Gastronomy. AI. Technology. I’m Kastriot Tafolli, bringing operational leadership and digital craft together – from restaurant service to intelligent systems.',hero_cta='Explore my portfolio',manifesto=['A host.','A developer.','One person.'],manifesto_text='I know guest service, the responsibility of leading teams and the numbers behind a business. I also build software and AI. That rare combination shapes my work.',manifesto_small='F&B consulting, supplier agreements and costing sit alongside digital transformation, cybersecurity and intelligent automation. I understand the business and can build the technology it needs.',services_label='THE PORTFOLIO / PRACTICE × TECHNOLOGY',services_title=['Many capabilities.','One perspective.'],portfolio_link='Explore all 22 service areas',about_text='I’m Kastriot Tafolli. From traditional service and leading multiple hotel outlets to software development and AI engineering: my experience connects people, operations and technology. I understand the work behind the processes I improve.',cta_text='F&B, purchasing, digital transformation or AI: tell me what you want to move forward in your business.'),
'sq':dict(title='Kastriot Tafolli · Hoteleri, gastronomi, IA & teknologji',description='Hoteleria dhe gastronomia takojnë IA dhe zhvillimin e softuerit: këshillim F&B, blerje, digjitalizim dhe AI Automation as a Service nga Kastriot Tafolli.',nav=['Shërbimet','Rreth meje','Njohuri','Kontakt'],hero_text='Hoteleri. Gastronomi. IA. Teknologji. Jam Kastriot Tafolli dhe lidh drejtimin operacional me zhvillimin digjital – nga puna në restorant te sistemet inteligjente.',hero_cta='Zbuloni portofolin tim',manifesto=['Mikpritës.','Zhvillues.','Një person.'],manifesto_text='Njoh shërbimin ndaj mysafirëve, përgjegjësinë për ekipet dhe shifrat pas një biznesi. Gjithashtu zhvilloj softuer dhe IA. Ky kombinim i rrallë përcakton punën time.',manifesto_small='Këshillimi F&B, marrëveshjet me furnitorët dhe kalkulimi lidhen me digjitalizimin, sigurinë kibernetike dhe automatizimin inteligjent. E kuptoj biznesin dhe ndërtoj teknologjinë që i nevojitet.',services_label='PORTOFOLI / PRAKTIKË × TEKNOLOGJI',services_title=['Shumë aftësi.','Një këndvështrim.'],portfolio_link='Zbuloni të 22 fushat e shërbimit',about_text='Jam Kastriot Tafolli. Nga shërbimi klasik dhe drejtimi i disa njësive hoteliere te zhvillimi i softuerit dhe inxhinieria e IA: përvoja ime lidh njerëzit, operacionet dhe teknologjinë. E njoh punën që qëndron pas proceseve.',cta_text='F&B, blerje, digjitalizim apo IA: më tregoni çfarë dëshironi të përmirësoni në biznesin tuaj.')}
for language,values in POSITIONING.items():
    COPY[language]['automation_description']=COPY[language]['description']
    COPY[language]['automation_hero_text']=COPY[language]['hero_text']
    COPY[language]['automation_cta']=COPY[language]['hero_cta']
    COPY[language].update(values)

COPY['de']['services'][1]=('02','F&B & HOSPITALITY','Bessere Abläufe. Bessere Zahlen.','Einkauf, Lieferantenvereinbarungen, Rückvergütungen, Kalkulation und operative Führung.','fb-beratung.html','F&B entdecken')
COPY['de']['services'][2]=('03','TECHNOLOGIE & DIGITAL','Der Betrieb. Weitergedacht.','Digitalisierung, Softwareentwicklung, Cybersecurity und ein digitaler Auftritt mit Persönlichkeit.','digitalisierung.html','Technologie entdecken')
COPY['en']['services'][2]=('03','TECHNOLOGY & DIGITAL','Your business. Reimagined.','Digital transformation, software development, cybersecurity and a distinctive online presence.','digitalisierung.html','Explore technology')
COPY['sq']['services'][2]=('03','TEKNOLOGJI & DIGJITAL','Biznesi juaj. I rimenduar.','Digjitalizim, zhvillim softueri, siguri kibernetike dhe një prezencë digjitale me karakter.','digitalisierung.html','Zbuloni teknologjinë')
