# -*- coding: utf-8 -*-
EN = {
"code": "en", "dir": "en", "name": "English", "locale": "en_GB",
"titel": "Kastriot Tafolli · Hospitality, Digital and Artificial Intelligence",
"beschreibung": "Fifteen years leading five-star hospitality, combined with training as a software engineer. F&B consulting, online marketing, AI automation and AI systems for hotels and restaurants.",

"nav": [("#felder","Services"),("#rechner","Calculators"),("#ablauf","Process"),("#wissen","Insights"),("../kontakt.html","Contact")],
"cta_nav": "Talk to me",
"skip": "Skip to content",
"menu_auf": "Open menu",

"hero_status": "Available for consulting",
"hero_orte": ["Baltic Sea, Rügen 54.4°N", "Schluchsee 47.8°N"],
"hero_h1": [["Five stars","in service."],["One line","in code."]],
"hero_text": "I am Kastriot Tafolli. Fifteen years leading five-star hospitality and training as a software engineer specialising in artificial intelligence. I get properties into operational shape, then build the systems that take the work off their hands.",
"hero_cta1": "Book a conversation", "hero_cta2": "Calculate savings",

"term_titel": "tafolli@ruegen ~ %",
"term": ["$ whoami","kastriot tafolli / f&b director + software engineer",
         "$ cat focus.txt","01 food and beverage leadership, five star",
         "02 purchasing, contracts, rebates","03 websites, seo, campaigns",
         "04 ai automation and custom software","$ ./teamo --status",
         "● online / 24 h / multilingual"],

"stats": [("200","+","people led at the same time"),
          ("50","+","apprentices trained"),
          ("15","+","years in five-star hospitality"),
          ("4","+","hotels run simultaneously")],
"sprachen_label": "Languages", "sprachen_wert": "DE · EN · SQ", "sprachen_stufe": "C2 / C1 / NATIVE",

"haeuser": ["Grand Hotel Binz","Cerês am Meer","Vier Jahreszeiten Binz","Rösing Touristik",
            "Raulff-Hotels","Vier Jahreszeiten am Schluchsee","Hotel Panorama Lohme",
            "Restaurant Wochenmarkt","Bukowina","Salsa Latino"],

"pos_tag": "Two languages, one head",
"pos_h2": [["This combination barely"],["exists in the industry."]],
"pos_text": "There are hoteliers who have never written a line of code. And there are agencies that have never built a staff rota. I stand in between, and that is exactly where the difference comes from.",
"pos_a_tag": "// on the floor", "pos_a_h3": "Hospitality is a craft.",
"pos_a_text": "It does not come from mission statements but from a hundred small things that have to be right every single evening. I have worked the pass, written rotas, run stocktakes and carried responsibility for star-level service.",
"pos_a_chips": ["Flambé","Banqueting","Michelin star","Half board","Rota","Stocktake","Food cost","Sommelier"],
"pos_b_tag": "// in the code", "pos_b_h3": "And software is a craft too.",
"pos_b_text": "I learned to program because I saw every day how much working time burns away in properties on tasks a machine could take over. Today I build exactly those machines.",

"felder_tag": "What I do",
"felder_h2": [["Four fields,"],["one signature."]],
"felder_text": "Most properties do not have one problem but several that hang together: food cost is off, visibility is missing, the team is drowning in enquiries, and too much work is still done by hand.",
"felder": [
  ("01","Operations","F&B consulting",
   "Beverage and supplier contracts, rebates, marketing allowances, food cost and processes that hold up in daily business.",
   ["Contracts with breweries and suppliers","Rebates, bonuses and allowances",
    "Food cost, costing, stocktaking","Interim F&B management"],
   "../fb-beratung.html","F&B consulting"),
  ("02","Digital","Online marketing & web",
   "Visibility that brings direct bookings instead of portal commission: website, search engines, campaigns, content and imagery.",
   ["Website and web development","SEO and local visibility",
    "Google Ads and social media","Photo, video and drone"],
   "../online-marketing.html","Digital services"),
  ("03","Automation","AI automation",
   "A machine takes over the work that repeats. I look at how the process actually runs, separate what can be automated from what needs judgement, and build only the part that pays for itself.",
   ["Automate processes instead of managing them","Read and classify documents",
    "Connect existing systems","Custom software, APIs and integrations"],
   "../kontakt.html","Discuss automation"),
  ("04","Artificial intelligence","TeamO, the digital AI colleague",
   "TeamO answers calls, replies to enquiries in several languages, maintains reservations and puts a finished daily report on the manager's desk every morning.",
   ["Calls and reservations around the clock","Email, WhatsApp, website chat and social media",
    "Daily reports, occupancy and revenue overview","Individually trained, connected in line with GDPR"],
   "../teamo-ki.html","Meet TeamO"),
],

"rech_tag": "Calculators",
"rech_h2": [["Run the numbers"],["before you talk to me."]],
"rech_text": "Four calculators, right in the browser: what does the telephone cost you? How much portal commission do you pay a year? What is sitting in your beverage contract? And what does posting regularly actually return? Every assumption is laid open.",
"rech_cta": "Open the calculators",
"rech_titel": "Worked example",
"rech_zeilen": [("45 calls + 70 messages a day","230 hrs/month"),
                ("of which taken over by AI","70 %"),
                ("900 room nights, 15 % commission","€129,195/year"),
                ("€180,000 beverage purchasing, 3 % instead of 8 %","€9,000/year")],
"rech_summe_label": "Order of magnitude per year", "rech_summe": "€94,467",

"abl_tag": "Working together",
"abl_h2": [["From the first conversation"],["to a measurable result."]],
"abl_text": "No standard package pulled over every property. I look at where you stand and work on what makes the biggest difference.",
"abl": [("01","Getting to know each other","A conversation with no obligation, by phone or on site. I listen, ask about numbers, team and processes, and say openly whether I am the right person."),
        ("02","Analysis and potential","I look at contracts, food cost, pricing, visibility and processes, and show where money is left on the table and where effort arises that need not exist."),
        ("03","Concept and priorities","You get a clear plan with measures, sequence, effort and expected effect. What works first comes first."),
        ("04","Implementation","I deliver, together with your team and my team at TB Solutions. Negotiations, website, campaigns, training and systems from one hand."),
        ("05","Review and adjustment","Results are measured and sharpened. On request I accompany your property permanently or take on interim F&B management.")],

"wis_tag": "Insights",
"wis_h2": [["What I have written down"],["from practice."]],
"wis": [("Artificial intelligence","What an AI colleague in a hotel really takes over",
         "There is a long way between chatbot marketing and operational reality. What actually works today, what does not, and where the line runs.","../wissen-ki-im-hotel.html"),
        ("Purchasing","The beverage contract nobody reads",
         "Rebates, bonuses, marketing allowances and sales support. How these systems work and why most businesses leave money lying there.","../wissen-getraenkevertrag.html"),
        ("Visibility","Why your guests book through a portal",
         "Fifteen percent commission is not a law of nature. What your own website has to deliver so guests land directly with you.","../wissen-direktbuchungen.html")],
"wis_lesen": "Read",

"zitat": "Advice, not patronising. I am always open to a conversation with no obligation.",
"zitat_quelle": "Kastriot Tafolli · TB Solutions",

"cta_tag": "// next step",
"cta_h2": [["Let us talk about your property."]],
"cta_text": "A first conversation takes half an hour and commits you to nothing. Afterwards you know whether and where I can help you.",
"cta_1": "Arrange a conversation", "cta_2": "Open the calculators",

"foot_text": "Hospitality leadership, digitalisation, AI automation and AI systems for hotels and restaurants.",
"foot_status": "TB SOLUTIONS · ONLINE",
"foot_sp1": "Pages",
"foot_l1": [("../ueber-mich.html","About me"),("../werdegang.html","Career"),("../leistungen.html","Services"),
            ("../teamo-ki.html","TeamO AI"),("../rechner.html","Calculators"),("../wissen.html","Insights"),
            ("../referenzen.html","References"),("../kontakt.html","Contact")],
"foot_sp2": "Focus areas",
"foot_l2": [("../fb-beratung.html","F&B consulting"),("../online-marketing.html","Online marketing & web"),
            ("../kontakt.html","AI automation"),("../teamo-ki.html","AI systems"),("../rechner.html","Calculators")],
"foot_sp3": "Contact",
"foot_adresse": ["Hauptstraße 1, 18609 Ostseebad Binz, Germany","Schluchsee, Black Forest"],
"foot_copy": "© 2026 Kastriot Tafolli · tafolli.net · Rügen / Schluchsee",
"foot_impressum": "Imprint", "foot_datenschutz": "Privacy",
"foot_shell": "$ hospitality --digital --ai",
}
