# -*- coding: utf-8 -*-
"""Deutscher Originalinhalt. Quelle der Wahrheit, EN und SQ sind Uebersetzungen."""

DE = {
"code": "de", "dir": "", "name": "Deutsch", "locale": "de_DE",
"titel": "Kastriot Tafolli · Gastronomie, Digitalisierung und Künstliche Intelligenz",
"beschreibung": "Fünfzehn Jahre Führung in der 5-Sterne-Hotellerie, verbunden mit einer Ausbildung zum Softwareingenieur. F&B-Beratung, Online-Marketing, KI-Automatisierung und KI-Lösungen für Hotels und Restaurants.",

"nav": [("#felder","Leistungen"),("#rechner","Rechner"),("#ablauf","Ablauf"),("#wissen","Wissen"),("kontakt.html","Kontakt")],
"cta_nav": "Gespräch",
"skip": "Zum Inhalt springen",
"menu_auf": "Menü öffnen",

"hero_status": "Verfügbar für Beratung",
"hero_orte": ["Ostseebad Rügen 54.4°N", "Schluchsee 47.8°N"],
"hero_h1": [["Fünf Sterne","im Service."],["Eine Zeile","im Code."]],
"hero_text": "Ich bin Kastriot Tafolli. Fünfzehn Jahre Führung in der 5-Sterne-Hotellerie und eine Ausbildung zum Softwareingenieur mit Schwerpunkt Künstliche Intelligenz. Ich bringe Häuser operativ in Form und baue die Systeme, die ihnen danach Arbeit abnehmen.",
"hero_cta1": "Beratungsgespräch", "hero_cta2": "Ersparnis berechnen",

"term_titel": "tafolli@rügen ~ %",
"term": ["$ whoami","kastriot tafolli / f&b direktor + software engineer",
         "$ cat schwerpunkte.txt","01 gastronomische leitung, 5 sterne plus",
         "02 einkauf, vertraege, rueckverguetungen","03 websites, seo, kampagnen",
         "04 ki-automatisierung und eigene software","$ ./teamo --status",
         "● online / 24 h / mehrsprachig"],

"stats": [("200","+","geführte Mitarbeitende, gleichzeitig"),
          ("50","+","ausgebildete Nachwuchskräfte"),
          ("15","+","Jahre 5-Sterne-Gastronomie"),
          ("4","+","Hotels zeitgleich geleitet")],
"sprachen_label": "Sprachen", "sprachen_wert": "DE · EN · SQ", "sprachen_stufe": "C2 / C1 / NATIV",

"haeuser": ["Grand Hotel Binz","Cerês am Meer","Vier Jahreszeiten Binz","Rösing Touristik",
            "Raulff-Hotels","Vier Jahreszeiten am Schluchsee","Hotel Panorama Lohme",
            "Restaurant Wochenmarkt","Bukowina","Salsa Latino"],

"pos_tag": "Zwei Sprachen, ein Kopf",
"pos_h2": [["Diese Kombination gibt es"],["in der Branche kaum."]],
"pos_text": "Es gibt Hoteliers, die keine Zeile Code schreiben. Und es gibt Agenturen, die noch nie einen Dienstplan gemacht haben. Ich stehe dazwischen, und genau daraus entsteht der Unterschied.",
"pos_a_tag": "// im haus", "pos_a_h3": "Gastfreundschaft ist Handwerk.",
"pos_a_text": "Sie entsteht nicht aus Leitbildern, sondern aus hundert Kleinigkeiten, die jeden Abend stimmen müssen. Ich habe am Pass gestanden, Dienstpläne geschrieben, Inventuren gemacht und Sterne-Service verantwortet.",
"pos_a_chips": ["Flambieren","Bankett","Michelin-Stern","Halbpension","Dienstplan","Inventur","Wareneinsatz","Sommelier"],
"pos_b_tag": "// im code", "pos_b_h3": "Und Software ist auch Handwerk.",
"pos_b_text": "Ich habe programmieren gelernt, weil ich jeden Tag gesehen habe, wie viel Arbeitszeit in Häusern verbrennt, die eine Maschine übernehmen könnte. Heute baue ich genau diese Maschinen.",

"felder_tag": "Leistungsfelder",
"felder_h2": [["Vier Felder,"],["eine Handschrift."]],
"felder_text": "Die meisten Häuser haben nicht ein Problem, sondern mehrere, die zusammenhängen: der Wareneinsatz stimmt nicht, die Sichtbarkeit fehlt, das Team ertrinkt in Anfragen und zu viel Arbeit läuft noch von Hand.",
"felder": [
  ("01","Operativ","F&B-Beratung",
   "Getränke- und Lieferverträge, Rückvergütungen, Marketingzuschüsse, Wareneinsatz und Abläufe, die im Tagesgeschäft tragen.",
   ["Verträge mit Brauereien und Lieferanten","Rückvergütungen, Boni und Zuschüsse",
    "Wareneinsatz, Kalkulation, Inventur","Externe F&B-Leitung auf Zeit"],
   "fb-beratung.html","F&B-Beratung"),
  ("02","Digital","Online-Marketing & Web",
   "Sichtbarkeit, die Direktbuchungen bringt statt Portalprovision: Website, Suchmaschinen, Kampagnen, Inhalte und Bilder.",
   ["Website und Webentwicklung","SEO und lokale Sichtbarkeit",
    "Google Ads und Social Media","Foto, Video und Drohne"],
   "online-marketing.html","Digitalleistungen"),
  ("03","Automatisierung","KI-Automatisierung",
   "Wiederkehrende Abläufe übernimmt eine Maschine. Ich sehe mir an, wie der Ablauf wirklich läuft, trenne das Automatisierbare vom Urteilsabhängigen und baue nur den Teil, der sich rechnet.",
   ["Abläufe automatisieren statt verwalten","Dokumente auslesen und einordnen",
    "Bestehende Systeme verbinden","Eigene Software, APIs und Schnittstellen"],
   "kontakt.html","Automatisierung besprechen"),
  ("04","Künstliche Intelligenz","TeamO, der digitale KI-Mitarbeiter",
   "TeamO nimmt Anrufe an, beantwortet Anfragen in mehreren Sprachen, pflegt Reservierungen und legt der Geschäftsführung morgens einen fertigen Tagesbericht hin.",
   ["Telefonate und Reservierungen rund um die Uhr","E-Mail, WhatsApp, Website-Chat und Social Media",
    "Tagesberichte, Auslastung und Umsatzübersicht","Individuell trainiert, datenschutzkonform angebunden"],
   "teamo-ki.html","TeamO kennenlernen"),
],

"rech_tag": "Rechner",
"rech_h2": [["Rechnen Sie nach,"],["bevor Sie mit mir reden."]],
"rech_text": "Vier Rechner, direkt im Browser: Was kostet Sie das Telefon? Wie viel Portalprovision zahlen Sie im Jahr? Was liegt in Ihrem Getränkevertrag? Und was bringt regelmäßiges Posten? Alle Annahmen sind offen gelegt.",
"rech_cta": "Zu den Rechnern",
"rech_titel": "Beispielrechnung",
"rech_zeilen": [("45 Anrufe + 70 Nachrichten täglich","230 Std./Monat"),
                ("davon durch KI übernommen","70 %"),
                ("900 Übernachtungen, 15 % Provision","129.195 €/Jahr"),
                ("180.000 € Getränkeeinkauf, 3 % statt 8 %","9.000 €/Jahr")],
"rech_summe_label": "Größenordnung pro Jahr", "rech_summe": "94.467 €",

"abl_tag": "Zusammenarbeit",
"abl_h2": [["Vom ersten Gespräch bis"],["zum messbaren Ergebnis."]],
"abl_text": "Kein Standardpaket, das über jedes Haus gestülpt wird. Ich sehe mir an, wo Sie stehen, und arbeite an dem, was den größten Unterschied macht.",
"abl": [("01","Kennenlernen und Bestandsaufnahme","Ein unverbindliches Gespräch, telefonisch oder vor Ort. Ich höre zu, stelle Fragen zu Zahlen, Team und Abläufen und sage offen, ob ich der Richtige bin."),
        ("02","Analyse und Potenziale","Ich sehe mir Verträge, Wareneinsatz, Preisstruktur, Sichtbarkeit und Prozesse an und zeige, wo Geld liegen bleibt und wo Aufwand entsteht, der nicht sein muss."),
        ("03","Konzept und Priorisierung","Sie bekommen einen klaren Plan mit Maßnahmen, Reihenfolge, Aufwand und erwartetem Effekt. Was zuerst wirkt, kommt zuerst."),
        ("04","Umsetzung","Ich setze um, gemeinsam mit Ihrem Team und meinem Team von TB Solutions. Verhandlungen, Website, Kampagnen, Schulungen und Systeme aus einer Hand."),
        ("05","Kontrolle und Nachjustierung","Ergebnisse werden gemessen und nachgeschärft. Auf Wunsch begleite ich Ihr Haus dauerhaft oder übernehme die F&B-Leitung auf Zeit.")],

"wis_tag": "Wissen",
"wis_h2": [["Was ich aus der Praxis"],["aufgeschrieben habe."]],
"wis": [("Künstliche Intelligenz","Was ein KI-Mitarbeiter im Hotel wirklich übernimmt",
         "Zwischen Chatbot-Marketing und Betriebsrealität liegt ein weiter Weg. Was heute tatsächlich funktioniert, was nicht, und wo die Grenze verläuft.","wissen-ki-im-hotel.html"),
        ("Einkauf","Der Getränkevertrag, den niemand liest",
         "Rückvergütungen, Boni, Marketingzuschüsse und Verkaufsförderung. Wie diese Systeme funktionieren und warum die meisten Betriebe Geld liegen lassen.","wissen-getraenkevertrag.html"),
        ("Sichtbarkeit","Warum Ihre Gäste über ein Portal buchen",
         "Fünfzehn Prozent Provision sind kein Naturgesetz. Was eine eigene Website leisten muss, damit Gäste direkt bei Ihnen landen.","wissen-direktbuchungen.html")],
"wis_lesen": "Lesen",

"zitat": "Beratung, keine Bevormundung. Ich bin immer offen für ein unverbindliches Gespräch.",
"zitat_quelle": "Kastriot Tafolli · TB Solutions",

"cta_tag": "// nächster schritt",
"cta_h2": [["Reden wir über Ihr Haus."]],
"cta_text": "Ein Erstgespräch kostet eine halbe Stunde und ist unverbindlich. Danach wissen Sie, ob und wo ich Ihnen helfen kann.",
"cta_1": "Beratungsgespräch vereinbaren", "cta_2": "Rechner öffnen",

"foot_text": "Gastronomische Führung, Digitalisierung, KI-Automatisierung und KI-Lösungen für Hotellerie und Gastronomie.",
"foot_status": "TB SOLUTIONS · ONLINE",
"foot_sp1": "Seiten",
"foot_l1": [("ueber-mich.html","Über mich"),("werdegang.html","Werdegang"),("leistungen.html","Leistungen"),
            ("teamo-ki.html","TeamO KI"),("rechner.html","Rechner"),("wissen.html","Wissen"),
            ("referenzen.html","Referenzen"),("kontakt.html","Kontakt")],
"foot_sp2": "Schwerpunkte",
"foot_l2": [("fb-beratung.html","F&B-Beratung"),("online-marketing.html","Online-Marketing & Web"),
            ("kontakt.html","KI-Automatisierung"),("teamo-ki.html","KI-Lösungen"),("rechner.html","Rechner")],
"foot_sp3": "Kontakt",
"foot_adresse": ["Hauptstraße 1, 18609 Ostseebad Binz","Schluchsee, Hochschwarzwald"],
"foot_copy": "© 2026 Kastriot Tafolli · tafolli.net · Ostseebad Rügen / Schluchsee",
"foot_impressum": "Impressum", "foot_datenschutz": "Datenschutz",
"foot_shell": "$ gastronomie --digital --ki",
}
