# -*- coding: utf-8 -*-
SQ = {
"code": "sq", "dir": "sq", "name": "Shqip", "locale": "sq_AL",
"titel": "Kastriot Tafolli · Hoteleri, digjitalizim dhe inteligjencë artificiale",
"beschreibung": "Pesëmbëdhjetë vjet drejtim në hotelerinë me pesë yje, i kombinuar me formimin si inxhinier softueri. Konsulencë F&B, marketing online, automatizim me IA dhe sisteme IA për hotele dhe restorante.",

"nav": [("../ueber-mich.html","Rreth meje"),("../werdegang.html","Karriera"),("../leistungen.html","Shërbimet"),("../teamo-ki.html","TeamO IA"),("../rechner.html","Llogaritësit"),("../wissen.html","Njohuri"),("../kontakt.html","Kontakt")],
"cta_nav": "Bisedë",
"skip": "Kalo te përmbajtja",
"menu_auf": "Hap menynë",

"hero_status": "I disponueshëm për konsulencë",
"hero_orte": ["Deti Baltik, Rügen 54.4°N", "Schluchsee 47.8°N"],
"hero_h1": [["Pesë yje","në shërbim."],["Një rresht","në kod."]],
"hero_text": "Unë jam Kastriot Tafolli. Pesëmbëdhjetë vjet drejtim në hotelerinë me pesë yje dhe formim si inxhinier softueri me fokus në inteligjencën artificiale. I vë bizneset në rregull nga ana operative dhe më pas ndërtoj sistemet që ua heqin punën nga supet.",
"hero_cta1": "Cakto një bisedë", "hero_cta2": "Llogarit kursimin",

"term_titel": "tafolli@ruegen ~ %",
"term": ["$ whoami","kastriot tafolli / drejtor f&b + inxhinier softueri",
         "$ cat fokusi.txt","01 drejtim gastronomie, pese yje",
         "02 blerje, kontrata, rimbursime","03 faqe interneti, seo, fushata",
         "04 automatizim me ia dhe softuer i vet","$ ./teamo --status",
         "● online / 24 h / shumegjuhesh"],

"stats": [("200","+","punonjës të drejtuar njëkohësisht"),
          ("50","+","praktikantë të trajnuar"),
          ("15","+","vjet në hoteleri me pesë yje"),
          ("4","+","hotele të drejtuara njëkohësisht")],
"sprachen_label": "Gjuhët", "sprachen_wert": "DE · EN · SQ", "sprachen_stufe": "C2 / C1 / AMTARE",

"haeuser": ["Grand Hotel Binz","Cerês am Meer","Vier Jahreszeiten Binz","Rösing Touristik",
            "Raulff-Hotels","Vier Jahreszeiten am Schluchsee","Hotel Panorama Lohme",
            "Restaurant Wochenmarkt","Bukowina","Salsa Latino"],

"pos_tag": "Dy gjuhë, një kokë",
"pos_h2": [["Ky kombinim gati"],["nuk ekziston në këtë fushë."]],
"pos_text": "Ka hotelierë që nuk kanë shkruar kurrë një rresht kod. Dhe ka agjenci që nuk kanë bërë kurrë një plan pune. Unë qëndroj midis tyre, dhe pikërisht prej andej vjen ndryshimi.",
"pos_a_tag": "// në sallë", "pos_a_h3": "Mikpritja është zanat.",
"pos_a_text": "Ajo nuk lind nga parimet e shkruara, por nga njëqind gjëra të vogla që duhet të jenë në rregull çdo mbrëmje. Kam qëndruar në kuzhinë, kam shkruar plane pune, kam bërë inventarë dhe kam mbajtur përgjegjësinë për shërbim me yje.",
"pos_a_chips": ["Flambé","Banket","Yll Michelin","Gjysmëpension","Plan pune","Inventar","Kosto malli","Someljé"],
"pos_b_tag": "// në kod", "pos_b_h3": "Edhe softueri është zanat.",
"pos_b_text": "Mësova programimin sepse shihja çdo ditë sa kohë pune digjet nëpër biznese për punë që një makinë mund t'i merrte përsipër. Sot i ndërtoj pikërisht ato makina.",

"ki_tag": "Automatizim me IA & Menaxhim i IA-s",
"ki_h2": [["Makina që punojnë."],["Njerëz që i drejtojnë."]],
"ki_lede": "Automatizimi pa mbikëqyrje është rrezik, jo zgjidhje. Unë ndërtoj të dyja: IA-n që merr përsipër punën, dhe strukturën që siguron se ajo vazhdon ta bëjë atë drejt.",
"ki_flip_label": "I automatizuar:",
"ki_flip_woerter": ["Telefonatat.", "Faturat.", "Raportet.", "Përgjigjet.", "Rezervimet.", "Të dhënat."],

"ki_pipeline": [
  ("Hyrja", "Telefonatë, email, formular, dokument"),
  ("Kuptimi", "Klasifikon përmbajtjen, njeh qëllimin"),
  ("Veprimi", "Përgjigjet, regjistron, përcjell"),
  ("Kontrolli", "Çdo dalje kontrollohet sipas rregullave"),
  ("Dalja", "Rezultati te marrësi, regjistrimi tek unë"),
],

"ki_a_tag": "// Automatizim", "ki_a_h3": "Çfarë merr përsipër një makinë.",
"ki_a_text": "Gjithçka që ndjek një model fiks: përgjigjen ndaj kërkesave, nxjerrjen e të dhënave nga dokumentet, mbajtjen e regjistrimeve, përpilimin e raporteve. IA punon gjatë gjithë kohës, pa pushim dhe pa rënie cilësie.",
"ki_b_tag": "// Menaxhim", "ki_b_h3": "Çfarë mbetet pas.",
"ki_b_text": "Një sistem që niset një herë nuk vazhdon vetë. Prompts vjetrohen, kostot dalin jashtë kontrollit, përgjigjet devijojnë. Unë marr përsipër kujdesin e vazhdueshëm: kontrolloj, përmirësoj, ndërhyj kur diçka nuk përshtatet më.",

"ki_showcase": [
  ("01", "Telefon & chat", "Merr telefonata, përgjigjet pyetjeve, mban biseda në disa gjuhë."),
  ("02", "Dokumente", "Lexon fatura, kontrata dhe formularë dhe i klasifikon automatikisht."),
  ("03", "Kutia e emailit", "Rendit mesazhet, dërgon përgjigje standarde, shënon urgjencat."),
  ("04", "Raporte", "Përpilon mbylljet ditore, analizat dhe shifrat automatikisht."),
  ("05", "Rezervime", "Kontrollon disponueshmërinë, konfirmon dhe i fut në sistemet ekzistuese."),
  ("06", "Sinkronizim të dhënash", "Mban sistemet në hap, zbulon dyfishimet, mbyll boshllëqet."),
  ("07", "Kontroll cilësie", "Çdo dalje kalon nga një kontroll para se të dërgohet."),
],

"ki_vgl_tag": "Para / Pas",
"ki_vgl_h3": "Ndryshimi ndihet, jo vetëm matet.",
"ki_vgl_ohne": "Pa automatizim",
"ki_vgl_mit": "Me automatizim me IA",
"ki_vgl_ohne_punkte": [
  "Çdo kërkesë ka nevojë për një person që ta lexojë",
  "Koha e përgjigjes varet nga disponueshmëria",
  "Gabimet shpesh dalin në pah vetëm te klienti",
  "Dija qëndron në kokën e punonjësve individualë",
],
"ki_vgl_mit_punkte": [
  "Kërkesave të përsëritura u përgjigjet IA direkt",
  "Përgjigje brenda sekondave, gjatë gjithë kohës",
  "Çdo dalje kontrollohet para se të dërgohet",
  "Dija qëndron në sistem, jo vetëm në një kokë",
],

"ki_dash_tag": "Pamje ilustruese",
"ki_dash_h3": "Si duket menaxhimi i IA-s në praktikë.",
"ki_dash_text": "Një fragment i mënyrës si shoqëroj një sistem në punë — çdo ditë, jo vetëm në fillim. Shifrat këtu janë shembull, jo të dhëna live.",
"ki_dash_status": "Online",
"ki_dash": [
  ("Përgjigje sot", "180", ""),
  ("Kontrolluar me dorë", "12", ""),
  ("Koha mesatare e përgjigjes", "2", " s"),
],
"ki_dash_letzte": "Kontrolli i fundit: sot, 07:40",
"ki_showcase_tag": "Shembuj nga praktika",
"ki_cta": "Bisedo për automatizimin",
"ki_cta_teamo": "Shiko TeamO si shembull",

"felder_tag": "Fushat e punës",
"felder_h2": [["Katër fusha,"],["një dorëshkrim."]],
"felder_text": "Shumica e bizneseve nuk kanë një problem, por disa që lidhen me njëri-tjetrin: kostoja e mallit nuk del, dukshmëria mungon, ekipi mbytet në kërkesa dhe shumë punë ende bëhet me dorë.",
"felder": [
  ("01","Operative","Konsulencë F&B",
   "Kontrata pijesh dhe furnitorësh, rimbursime, mbështetje marketingu, kosto malli dhe procese që mbajnë në punën e përditshme.",
   ["Kontrata me birrari dhe furnitorë","Rimbursime, bonuse dhe mbështetje",
    "Kosto malli, kalkulim, inventar","Drejtim F&B i përkohshëm nga jashtë"],
   "../fb-beratung.html","Konsulencë F&B"),
  ("02","Digjitale","Marketing online dhe web",
   "Dukshmëri që sjell rezervime të drejtpërdrejta në vend të komisionit të portaleve: faqe interneti, motorë kërkimi, fushata, përmbajtje dhe fotografi.",
   ["Faqe interneti dhe zhvillim web","SEO dhe dukshmëri lokale",
    "Google Ads dhe rrjete sociale","Foto, video dhe dron"],
   "../online-marketing.html","Shërbime digjitale"),
  ("03","Inteligjencë artificiale","TeamO, kolegu digjital me IA",
   "TeamO u përgjigjet telefonatave, kthen përgjigje në disa gjuhë, mban rezervimet dhe i lë drejtuesit çdo mëngjes një raport ditor të gatshëm. Produkti konkret i ndërtuar nga automatizimi dhe menaxhimi i IA-s të përshkruara më sipër.",
   ["Telefonata dhe rezervime gjatë gjithë kohës","Email, WhatsApp, chat në faqe dhe rrjete sociale",
    "Raporte ditore, shfrytëzim dhe pasqyrë xhiroje","I trajnuar veçmas, i lidhur sipas GDPR"],
   "../teamo-ki.html","Njihu me TeamO"),
],

"rech_tag": "Llogaritësit",
"rech_h2": [["Bëni llogaritë"],["para se të flisni me mua."]],
"rech_text": "Katër llogaritës, drejt e në shfletues: sa ju kushton telefoni? Sa komision portalesh paguani në vit? Çfarë fshihet në kontratën tuaj të pijeve? Dhe çfarë sjell postimi i rregullt? Të gjitha supozimet janë të hapura.",
"rech_cta": "Shko te llogaritësit",
"rech_titel": "Shembull llogaritjeje",
"rech_zeilen": [("45 telefonata + 70 mesazhe në ditë","230 orë/muaj"),
                ("prej tyre të marra nga IA","70 %"),
                ("900 netë qëndrimi, 15 % komision","129.195 €/vit"),
                ("180.000 € blerje pijesh, 3 % në vend të 8 %","9.000 €/vit")],
"rech_summe_label": "Madhësia për vit", "rech_summe": "94.467 €",

"abl_tag": "Bashkëpunimi",
"abl_h2": [["Nga biseda e parë"],["te një rezultat i matshëm."]],
"abl_text": "Asnjë paketë standarde që i vihet çdo biznesi. Shoh ku ndodheni dhe punoj për atë që sjell ndryshimin më të madh.",
"abl": [("01","Njohja dhe gjendja aktuale","Një bisedë pa detyrim, me telefon ose në vend. Dëgjoj, pyes për shifrat, ekipin dhe proceset, dhe them hapur nëse jam personi i duhur."),
        ("02","Analiza dhe potenciali","Shoh kontratat, koston e mallit, strukturën e çmimeve, dukshmërinë dhe proceset, dhe tregoj ku mbetet para dhe ku lind punë që nuk duhej të ekzistonte."),
        ("03","Koncepti dhe prioritetet","Merrni një plan të qartë me masa, radhë, përpjekje dhe efekt të pritshëm. Ajo që vepron e para, vjen e para."),
        ("04","Zbatimi","Zbatoj së bashku me ekipin tuaj dhe ekipin tim në TB Solutions. Negociata, faqe interneti, fushata, trajnime dhe sisteme nga një dorë."),
        ("05","Kontrolli dhe rregullimi","Rezultatet maten dhe përmirësohen. Me kërkesë e shoqëroj biznesin tuaj në vazhdimësi ose marr drejtimin e përkohshëm të F&B.")],

"wis_tag": "Njohuri",
"wis_h2": [["Çfarë kam shkruar"],["nga praktika."]],
"wis": [("Inteligjencë artificiale","Çfarë merr përsipër vërtet një koleg me IA në hotel",
         "Midis marketingut me chatbot dhe realitetit të punës ka një rrugë të gjatë. Çfarë funksionon sot vërtet, çfarë jo, dhe ku kalon kufiri.","../wissen-ki-im-hotel.html"),
        ("Blerje","Kontrata e pijeve që askush nuk e lexon",
         "Rimbursime, bonuse, mbështetje marketingu dhe nxitje shitjeje. Si funksionojnë këto sisteme dhe pse shumica e bizneseve lënë para pas dore.","../wissen-getraenkevertrag.html"),
        ("Dukshmëri","Pse mysafirët tuaj rezervojnë përmes një portali",
         "Pesëmbëdhjetë për qind komision nuk është ligj natyre. Çfarë duhet të ofrojë faqja juaj që mysafirët të vijnë drejtpërdrejt te ju.","../wissen-direktbuchungen.html")],
"wis_lesen": "Lexo",

"faq_tag": "Pyetje",
"faq_h2": [["Çfarë pyetet"],["zakonisht e para."]],
"faq": [
  ("Sa kushton një automatizim?",
   "Kjo varet nga sa sisteme duhen lidhur dhe sa kontroll kërkon një proces. Një proces i vetëm, i përcaktuar qartë, kushton dukshëm më pak se një automatizim që përshkon disa departamente. Pas bisedës së parë jap një interval, jo një shifër të trilluar."),
  ("Sa kohë deri sa diçka të funksionojë?",
   "Versioni i parë i përdorshëm vjen brenda javësh, jo muajsh. Ndërtoj qëllimisht së pari pjesën më të vogël që tashmë heq punë nga duart tuaja, dhe zgjerohem nga aty — jo gjashtë muaj zhvillim pa asnjë rezultat të ndërmjetëm."),
  ("A qëndrojnë të dhënat brenda shtëpisë?",
   "Ku është e mundur, po. Çfarë mund të përpunohet lokalisht, përpunohet lokalisht. Nëse nevojitet një model gjuhësor i një ofruesi, them hapur më parë çfarë të dhënash sheh, dhe përpunimi rregullohet sipas GDPR-së."),
  ("Çfarë ndodh kur IA gabon?",
   "Kjo ndërtohet që në fillim, jo më vonë. Çdo dalje që shkon jashtë ose shkruan në një sistem merr një kontroll më parë. Çfarë është e pasigurt përfundon te një person, jo te klienti — kjo është thelbi i menaxhimit të IA-s."),
  ("Çfarë ndodh pasi një sistem fillon punën?",
   "Vëzhgohet. Kontrolloj rregullisht nëse përgjigjet janë ende të sakta, nëse kërkesat kanë ndryshuar, dhe e përmirësoj para se një devijim i vogël të bëhet problem i vërtetë."),
  ("A më duhet ekip i vetin për këtë?",
   "Jo. Pikërisht kjo është kuptimi i menaxhimit të IA-s si shërbim: merrni një sistem në punë pa pasur nevojë që dikush brenda biznesit tuaj ta kontrollojë çdo ditë."),
  ("A punoni edhe me kod ekzistues?",
   "Po. Zgjerimi i një aplikacioni ekzistues, ndërtimi i një funksioni IA brenda një sistemi në punë, ose bërja gati për prodhim e një prototipi — kjo ndodh më shpesh se një projekt nga zero."),
],

"zitat": "Këshillim, jo imponim. Jam gjithmonë i hapur për një bisedë pa detyrim.",
"zitat_quelle": "Kastriot Tafolli · TB Solutions",

"cta_tag": "// hapi tjetër",
"cta_h2": [["Le të flasim për biznesin tuaj."]],
"cta_text": "Biseda e parë zgjat gjysmë ore dhe nuk ju detyron me asgjë. Pas saj e dini nëse dhe ku mund t'ju ndihmoj.",
"cta_1": "Cakto një bisedë", "cta_2": "Hap llogaritësit",

"foot_text": "Drejtim gastronomie, digjitalizim, automatizim me IA dhe sisteme IA për hoteleri dhe gastronomi.",
"foot_status": "TB SOLUTIONS · ONLINE",
"foot_sp1": "Faqet",
"foot_l1": [("../ueber-mich.html","Rreth meje"),("../werdegang.html","Karriera"),("../leistungen.html","Shërbimet"),
            ("../teamo-ki.html","TeamO IA"),("../rechner.html","Llogaritësit"),("../wissen.html","Njohuri"),
            ("../referenzen.html","Referenca"),("../kontakt.html","Kontakt")],
"foot_sp2": "Fushat",
"foot_l2": [("../fb-beratung.html","Konsulencë F&B"),("../online-marketing.html","Marketing online dhe web"),
            ("#ki","Automatizim me IA"),("../teamo-ki.html","Sisteme IA"),("../rechner.html","Llogaritësit")],
"foot_sp3": "Kontakt",
"foot_adresse": ["Hauptstraße 1, 18609 Ostseebad Binz, Gjermani","Schluchsee, Pylli i Zi"],
"foot_copy": "© 2026 Kastriot Tafolli · tafolli.net · Rügen / Schluchsee",
"foot_impressum": "Impressum", "foot_datenschutz": "Privatësia",
"foot_shell": "$ hoteleri --digjitale --ia",
}
