# -*- coding: utf-8 -*-
EN = {
"code": "en", "dir": "en", "name": "English", "locale": "en_GB",
"titel": "Kastriot Tafolli · Hospitality, Digital and Artificial Intelligence",
"beschreibung": "Fifteen years leading five-star hospitality, combined with training as a software engineer. F&B consulting, online marketing, AI automation and AI systems for hotels and restaurants.",

"nav": [("../ueber-mich.html","About"),("../werdegang.html","Career"),("../leistungen.html","Services"),("../teamo-ki.html","TeamO AI"),("../rechner.html","Calculators"),("../wissen.html","Insights"),("../kontakt.html","Contact")],
"cta_nav": "Talk to me",
"skip": "Skip to content",
"menu_auf": "Open menu",

"hero_status": "Available for consulting",
"hero_orte": ["Baltic Sea, Rügen 54.4°N", "Schluchsee 47.8°N"],
"hero_h1": [["Five stars","in service."],["One line","in code."]],
"hero_text": "I am Kastriot Tafolli. Fifteen years leading five-star hospitality and training as a software engineer specialising in artificial intelligence. I get properties into operational shape, then build the systems that take the work off their hands.",
"hero_cta1": "Book a conversation", "hero_cta2": "Calculate savings",

"term_titel": "tafolli@ruegen ~ %",
"term": ["$ whoami","kastriot tafolli / f&b director + software engineer",
         "$ cat focus.txt","01 food and beverage leadership, five star",
         "02 purchasing, contracts, rebates","03 websites, seo, campaigns",
         "04 ai automation and custom software","$ ./teamo --status",
         "● online / 24 h / multilingual"],

"stats": [("200","+","people led at the same time"),
          ("50","+","apprentices trained"),
          ("15","+","years in five-star hospitality"),
          ("4","+","hotels run simultaneously")],
"sprachen_label": "Languages", "sprachen_wert": "DE · EN · SQ", "sprachen_stufe": "C2 / C1 / NATIVE",

"haeuser": ["Grand Hotel Binz","Cerês am Meer","Vier Jahreszeiten Binz","Rösing Touristik",
            "Raulff-Hotels","Vier Jahreszeiten am Schluchsee","Hotel Panorama Lohme",
            "Restaurant Wochenmarkt","Bukowina","Salsa Latino"],

"pos_tag": "Two languages, one head",
"pos_h2": [["This combination barely"],["exists in the industry."]],
"pos_text": "There are hoteliers who have never written a line of code. And there are agencies that have never built a staff rota. I stand in between, and that is exactly where the difference comes from.",
"pos_a_tag": "// on the floor", "pos_a_h3": "Hospitality is a craft.",
"pos_a_text": "It does not come from mission statements but from a hundred small things that have to be right every single evening. I have worked the pass, written rotas, run stocktakes and carried responsibility for star-level service.",
"pos_a_chips": ["Flambé","Banqueting","Michelin star","Half board","Rota","Stocktake","Food cost","Sommelier"],
"pos_b_tag": "// in the code", "pos_b_h3": "And software is a craft too.",
"pos_b_text": "I learned to program because I saw every day how much working time burns away in properties on tasks a machine could take over. Today I build exactly those machines.",

"ki_tag": "AI Automation & AI Management",
"ki_h2": [["Machines that work."],["People who run them."]],
"ki_lede": "Automation without oversight is a risk, not a solution. I build both: the AI that takes over the work, and the structure that keeps it doing that work correctly.",
"ki_flip_label": "Automated:",
"ki_flip_woerter": ["Calls.", "Invoices.", "Reports.", "Replies.", "Bookings.", "Data."],

"ki_pipeline": [
  ("Input", "Call, email, form, document"),
  ("Understand", "Classify content, read intent"),
  ("Act", "Reply, log, forward"),
  ("Check", "Every output checked against rules"),
  ("Output", "Result with the recipient, a record with me"),
],

"ki_a_tag": "// Automation", "ki_a_h3": "What a machine takes over.",
"ki_a_text": "Everything that follows a fixed pattern: answering enquiries, pulling data from documents, keeping records, assembling reports. The AI works around the clock, without breaks and without a dip in quality.",
"ki_b_tag": "// Management", "ki_b_h3": "What is still left to do afterwards.",
"ki_b_text": "A system that runs once does not keep running on its own. Prompts go stale, costs drift, answers degrade. I take on the ongoing care: checking, sharpening, stepping in when something no longer fits.",

"ki_showcase": [
  ("01", "Phone & chat", "Answer calls, handle questions, hold conversations in several languages."),
  ("02", "Documents", "Read invoices, contracts and forms and file them automatically."),
  ("03", "Email inbox", "Sort messages, send standard replies, flag what is urgent."),
  ("04", "Reports", "Assemble daily closes, analyses and figures automatically."),
  ("05", "Bookings", "Check availability, confirm, and enter it into existing systems."),
  ("06", "Data sync", "Keep systems in step, catch duplicates, close gaps."),
  ("07", "Quality check", "Every output runs through a check before it goes out."),
],

"ki_vgl_tag": "Before / After",
"ki_vgl_h3": "The difference is felt, not only measured.",
"ki_vgl_ohne": "Without automation",
"ki_vgl_mit": "With AI automation",
"ki_vgl_ohne_punkte": [
  "Every enquiry needs a person to read it",
  "Response time depends on who is available",
  "Mistakes often surface only with the customer",
  "Knowledge lives in individual people's heads",
],
"ki_vgl_mit_punkte": [
  "Recurring enquiries get answered by the AI directly",
  "A reply in seconds, around the clock",
  "Every output is checked before it goes out",
  "Knowledge lives in the system, not only in a head",
],

"ki_dash_tag": "Illustrative view",
"ki_dash_h3": "What AI management looks like in practice.",
"ki_dash_text": "A glimpse of how I accompany a running system — daily, not only at launch. The figures here are an example, not live data.",
"ki_dash_status": "Online",
"ki_dash": [
  ("Replies today", "180", ""),
  ("Checked by hand", "12", ""),
  ("Average response time", "2", " s"),
],
"ki_dash_letzte": "Last review: today, 07:40",
"ki_showcase_tag": "Examples from practice",
"ki_cta": "Discuss automation",
"ki_cta_teamo": "See TeamO as an example",

"felder_tag": "What I do",
"felder_h2": [["Four fields,"],["one signature."]],
"felder_text": "Most properties do not have one problem but several that hang together: food cost is off, visibility is missing, the team is drowning in enquiries, and too much work is still done by hand.",
"felder": [
  ("01","Operations","F&B consulting",
   "Beverage and supplier contracts, rebates, marketing allowances, food cost and processes that hold up in daily business.",
   ["Contracts with breweries and suppliers","Rebates, bonuses and allowances",
    "Food cost, costing, stocktaking","Interim F&B management"],
   "../fb-beratung.html","F&B consulting"),
  ("02","Digital","Online marketing & web",
   "Visibility that brings direct bookings instead of portal commission: website, search engines, campaigns, content and imagery.",
   ["Website and web development","SEO and local visibility",
    "Google Ads and social media","Photo, video and drone"],
   "../online-marketing.html","Digital services"),
  ("03","Artificial intelligence","TeamO, the digital AI colleague",
   "TeamO answers calls, replies to enquiries in several languages, maintains reservations and puts a finished daily report on the manager's desk every morning. The concrete product built from the AI automation and AI management described above.",
   ["Calls and reservations around the clock","Email, WhatsApp, website chat and social media",
    "Daily reports, occupancy and revenue overview","Individually trained, connected in line with GDPR"],
   "../teamo-ki.html","Meet TeamO"),
],

"rech_tag": "Calculators",
"rech_h2": [["Run the numbers"],["before you talk to me."]],
"rech_text": "Four calculators, right in the browser: what does the telephone cost you? How much portal commission do you pay a year? What is sitting in your beverage contract? And what does posting regularly actually return? Every assumption is laid open.",
"rech_cta": "Open the calculators",
"rech_titel": "Worked example",
"rech_zeilen": [("45 calls + 70 messages a day","230 hrs/month"),
                ("of which taken over by AI","70 %"),
                ("900 room nights, 15 % commission","€129,195/year"),
                ("€180,000 beverage purchasing, 3 % instead of 8 %","€9,000/year")],
"rech_summe_label": "Order of magnitude per year", "rech_summe": "€94,467",

"abl_tag": "Working together",
"abl_h2": [["From the first conversation"],["to a measurable result."]],
"abl_text": "No standard package pulled over every property. I look at where you stand and work on what makes the biggest difference.",
"abl": [("01","Getting to know each other","A conversation with no obligation, by phone or on site. I listen, ask about numbers, team and processes, and say openly whether I am the right person."),
        ("02","Analysis and potential","I look at contracts, food cost, pricing, visibility and processes, and show where money is left on the table and where effort arises that need not exist."),
        ("03","Concept and priorities","You get a clear plan with measures, sequence, effort and expected effect. What works first comes first."),
        ("04","Implementation","I deliver, together with your team and my team at TB Solutions. Negotiations, website, campaigns, training and systems from one hand."),
        ("05","Review and adjustment","Results are measured and sharpened. On request I accompany your property permanently or take on interim F&B management.")],

"wis_tag": "Insights",
"wis_h2": [["What I have written down"],["from practice."]],
"wis": [("Artificial intelligence","What an AI colleague in a hotel really takes over",
         "There is a long way between chatbot marketing and operational reality. What actually works today, what does not, and where the line runs.","../wissen-ki-im-hotel.html"),
        ("Purchasing","The beverage contract nobody reads",
         "Rebates, bonuses, marketing allowances and sales support. How these systems work and why most businesses leave money lying there.","../wissen-getraenkevertrag.html"),
        ("Visibility","Why your guests book through a portal",
         "Fifteen percent commission is not a law of nature. What your own website has to deliver so guests land directly with you.","../wissen-direktbuchungen.html")],
"wis_lesen": "Read",

"faq_tag": "Questions",
"faq_h2": [["What usually gets"],["asked first."]],
"faq": [
  ("What does an automation cost?",
   "That depends on how many systems need connecting and how much checking a process needs. A single, clearly scoped process sits well below an automation that runs across several departments. After the first conversation I name a range, not a made-up figure."),
  ("How long before something is running?",
   "The first usable version is live in weeks, not months. I deliberately build the smallest part that already takes work off your hands first, and extend from there — not six months of development with nothing to show."),
  ("Does the data stay in-house?",
   "Where possible, yes. What can be processed locally is processed locally. If a provider's language model is needed, I say upfront which data it sees, and processing is set up under GDPR."),
  ("What happens when the AI gets something wrong?",
   "It is built around that from the start, not patched afterwards. Every output that goes out or writes into a system gets a check beforehand. Whatever is uncertain lands with a person, not with the customer — that is the core of AI management."),
  ("What happens after a system is running?",
   "It gets watched. I check regularly whether the answers still hold, whether enquiries have shifted, and sharpen it before a small drift becomes a real problem."),
  ("Do I need my own team for that?",
   "No. That is exactly the point of AI management as a service: you get a running system without anyone in-house having to check on it every day."),
  ("Do you also work on existing code?",
   "Yes. Extending an existing application, building an AI feature into a running system, or making a prototype production-ready — that happens more often than a project from zero."),
],

"zitat": "Advice, not patronising. I am always open to a conversation with no obligation.",
"zitat_quelle": "Kastriot Tafolli · TB Solutions",

"cta_tag": "// next step",
"cta_h2": [["Let us talk about your property."]],
"cta_text": "A first conversation takes half an hour and commits you to nothing. Afterwards you know whether and where I can help you.",
"cta_1": "Arrange a conversation", "cta_2": "Open the calculators",

"foot_text": "Hospitality leadership, digitalisation, AI automation and AI systems for hotels and restaurants.",
"foot_status": "TB SOLUTIONS · ONLINE",
"foot_sp1": "Pages",
"foot_l1": [("../ueber-mich.html","About me"),("../werdegang.html","Career"),("../leistungen.html","Services"),
            ("../teamo-ki.html","TeamO AI"),("../rechner.html","Calculators"),("../wissen.html","Insights"),
            ("../referenzen.html","References"),("../kontakt.html","Contact")],
"foot_sp2": "Focus areas",
"foot_l2": [("../fb-beratung.html","F&B consulting"),("../online-marketing.html","Online marketing & web"),
            ("#ki","AI automation"),("../teamo-ki.html","AI systems"),("../rechner.html","Calculators")],
"foot_sp3": "Contact",
"foot_adresse": ["Hauptstraße 1, 18609 Ostseebad Binz, Germany","Schluchsee, Black Forest"],
"foot_copy": "© 2026 Kastriot Tafolli · tafolli.net · Rügen / Schluchsee",
"foot_impressum": "Imprint", "foot_datenschutz": "Privacy",
"foot_shell": "$ hospitality --digital --ai",
}
