# -*- coding: utf-8 -*-
SQ = {
"code": "sq", "dir": "sq", "name": "Shqip", "locale": "sq_AL",
"titel": "Kastriot Tafolli · Hoteleri, digjitalizim dhe inteligjencë artificiale",
"beschreibung": "Pesëmbëdhjetë vjet drejtim në hotelerinë me pesë yje, i kombinuar me formimin si inxhinier softueri. Konsulencë F&B, marketing online, automatizim me IA dhe sisteme IA për hotele dhe restorante.",

"nav": [("#felder","Shërbimet"),("#rechner","Llogaritësit"),("#ablauf","Procesi"),("#wissen","Njohuri"),("../kontakt.html","Kontakt")],
"cta_nav": "Bisedë",
"skip": "Kalo te përmbajtja",
"menu_auf": "Hap menynë",

"hero_status": "I disponueshëm për konsulencë",
"hero_orte": ["Deti Baltik, Rügen 54.4°N", "Schluchsee 47.8°N"],
"hero_h1": [["Pesë yje","në shërbim."],["Një rresht","në kod."]],
"hero_text": "Unë jam Kastriot Tafolli. Pesëmbëdhjetë vjet drejtim në hotelerinë me pesë yje dhe formim si inxhinier softueri me fokus në inteligjencën artificiale. I vë bizneset në rregull nga ana operative dhe më pas ndërtoj sistemet që ua heqin punën nga supet.",
"hero_cta1": "Cakto një bisedë", "hero_cta2": "Llogarit kursimin",

"term_titel": "tafolli@ruegen ~ %",
"term": ["$ whoami","kastriot tafolli / drejtor f&b + inxhinier softueri",
         "$ cat fokusi.txt","01 drejtim gastronomie, pese yje",
         "02 blerje, kontrata, rimbursime","03 faqe interneti, seo, fushata",
         "04 automatizim me ia dhe softuer i vet","$ ./teamo --status",
         "● online / 24 h / shumegjuhesh"],

"stats": [("200","+","punonjës të drejtuar njëkohësisht"),
          ("50","+","praktikantë të trajnuar"),
          ("15","+","vjet në hoteleri me pesë yje"),
          ("4","+","hotele të drejtuara njëkohësisht")],
"sprachen_label": "Gjuhët", "sprachen_wert": "DE · EN · SQ", "sprachen_stufe": "C2 / C1 / AMTARE",

"haeuser": ["Grand Hotel Binz","Cerês am Meer","Vier Jahreszeiten Binz","Rösing Touristik",
            "Raulff-Hotels","Vier Jahreszeiten am Schluchsee","Hotel Panorama Lohme",
            "Restaurant Wochenmarkt","Bukowina","Salsa Latino"],

"pos_tag": "Dy gjuhë, një kokë",
"pos_h2": [["Ky kombinim gati"],["nuk ekziston në këtë fushë."]],
"pos_text": "Ka hotelierë që nuk kanë shkruar kurrë një rresht kod. Dhe ka agjenci që nuk kanë bërë kurrë një plan pune. Unë qëndroj midis tyre, dhe pikërisht prej andej vjen ndryshimi.",
"pos_a_tag": "// në sallë", "pos_a_h3": "Mikpritja është zanat.",
"pos_a_text": "Ajo nuk lind nga parimet e shkruara, por nga njëqind gjëra të vogla që duhet të jenë në rregull çdo mbrëmje. Kam qëndruar në kuzhinë, kam shkruar plane pune, kam bërë inventarë dhe kam mbajtur përgjegjësinë për shërbim me yje.",
"pos_a_chips": ["Flambé","Banket","Yll Michelin","Gjysmëpension","Plan pune","Inventar","Kosto malli","Someljé"],
"pos_b_tag": "// në kod", "pos_b_h3": "Edhe softueri është zanat.",
"pos_b_text": "Mësova programimin sepse shihja çdo ditë sa kohë pune digjet nëpër biznese për punë që një makinë mund t'i merrte përsipër. Sot i ndërtoj pikërisht ato makina.",

"felder_tag": "Fushat e punës",
"felder_h2": [["Katër fusha,"],["një dorëshkrim."]],
"felder_text": "Shumica e bizneseve nuk kanë një problem, por disa që lidhen me njëri-tjetrin: kostoja e mallit nuk del, dukshmëria mungon, ekipi mbytet në kërkesa dhe shumë punë ende bëhet me dorë.",
"felder": [
  ("01","Operative","Konsulencë F&B",
   "Kontrata pijesh dhe furnitorësh, rimbursime, mbështetje marketingu, kosto malli dhe procese që mbajnë në punën e përditshme.",
   ["Kontrata me birrari dhe furnitorë","Rimbursime, bonuse dhe mbështetje",
    "Kosto malli, kalkulim, inventar","Drejtim F&B i përkohshëm nga jashtë"],
   "../fb-beratung.html","Konsulencë F&B"),
  ("02","Digjitale","Marketing online dhe web",
   "Dukshmëri që sjell rezervime të drejtpërdrejta në vend të komisionit të portaleve: faqe interneti, motorë kërkimi, fushata, përmbajtje dhe fotografi.",
   ["Faqe interneti dhe zhvillim web","SEO dhe dukshmëri lokale",
    "Google Ads dhe rrjete sociale","Foto, video dhe dron"],
   "../online-marketing.html","Shërbime digjitale"),
  ("03","Automatizim","Automatizim me IA",
   "Punët që përsëriten i merr përsipër një makinë. Shoh si rrjedh procesi në të vërtetë, ndaj atë që automatizohet nga ajo që kërkon gjykim, dhe ndërtoj vetëm pjesën që ia vlen.",
   ["Automatizo procese në vend që t'i administrosh","Lexo dhe klasifiko dokumente",
    "Lidh sistemet ekzistuese","Softuer i posaçëm, API dhe integrime"],
   "../kontakt.html","Bisedo për automatizimin"),
  ("04","Inteligjencë artificiale","TeamO, kolegu digjital me IA",
   "TeamO u përgjigjet telefonatave, kthen përgjigje në disa gjuhë, mban rezervimet dhe i lë drejtuesit çdo mëngjes një raport ditor të gatshëm.",
   ["Telefonata dhe rezervime gjatë gjithë kohës","Email, WhatsApp, chat në faqe dhe rrjete sociale",
    "Raporte ditore, shfrytëzim dhe pasqyrë xhiroje","I trajnuar veçmas, i lidhur sipas GDPR"],
   "../teamo-ki.html","Njihu me TeamO"),
],

"rech_tag": "Llogaritësit",
"rech_h2": [["Bëni llogaritë"],["para se të flisni me mua."]],
"rech_text": "Katër llogaritës, drejt e në shfletues: sa ju kushton telefoni? Sa komision portalesh paguani në vit? Çfarë fshihet në kontratën tuaj të pijeve? Dhe çfarë sjell postimi i rregullt? Të gjitha supozimet janë të hapura.",
"rech_cta": "Shko te llogaritësit",
"rech_titel": "Shembull llogaritjeje",
"rech_zeilen": [("45 telefonata + 70 mesazhe në ditë","230 orë/muaj"),
                ("prej tyre të marra nga IA","70 %"),
                ("900 netë qëndrimi, 15 % komision","129.195 €/vit"),
                ("180.000 € blerje pijesh, 3 % në vend të 8 %","9.000 €/vit")],
"rech_summe_label": "Madhësia për vit", "rech_summe": "94.467 €",

"abl_tag": "Bashkëpunimi",
"abl_h2": [["Nga biseda e parë"],["te një rezultat i matshëm."]],
"abl_text": "Asnjë paketë standarde që i vihet çdo biznesi. Shoh ku ndodheni dhe punoj për atë që sjell ndryshimin më të madh.",
"abl": [("01","Njohja dhe gjendja aktuale","Një bisedë pa detyrim, me telefon ose në vend. Dëgjoj, pyes për shifrat, ekipin dhe proceset, dhe them hapur nëse jam personi i duhur."),
        ("02","Analiza dhe potenciali","Shoh kontratat, koston e mallit, strukturën e çmimeve, dukshmërinë dhe proceset, dhe tregoj ku mbetet para dhe ku lind punë që nuk duhej të ekzistonte."),
        ("03","Koncepti dhe prioritetet","Merrni një plan të qartë me masa, radhë, përpjekje dhe efekt të pritshëm. Ajo që vepron e para, vjen e para."),
        ("04","Zbatimi","Zbatoj së bashku me ekipin tuaj dhe ekipin tim në TB Solutions. Negociata, faqe interneti, fushata, trajnime dhe sisteme nga një dorë."),
        ("05","Kontrolli dhe rregullimi","Rezultatet maten dhe përmirësohen. Me kërkesë e shoqëroj biznesin tuaj në vazhdimësi ose marr drejtimin e përkohshëm të F&B.")],

"wis_tag": "Njohuri",
"wis_h2": [["Çfarë kam shkruar"],["nga praktika."]],
"wis": [("Inteligjencë artificiale","Çfarë merr përsipër vërtet një koleg me IA në hotel",
         "Midis marketingut me chatbot dhe realitetit të punës ka një rrugë të gjatë. Çfarë funksionon sot vërtet, çfarë jo, dhe ku kalon kufiri.","../wissen-ki-im-hotel.html"),
        ("Blerje","Kontrata e pijeve që askush nuk e lexon",
         "Rimbursime, bonuse, mbështetje marketingu dhe nxitje shitjeje. Si funksionojnë këto sisteme dhe pse shumica e bizneseve lënë para pas dore.","../wissen-getraenkevertrag.html"),
        ("Dukshmëri","Pse mysafirët tuaj rezervojnë përmes një portali",
         "Pesëmbëdhjetë për qind komision nuk është ligj natyre. Çfarë duhet të ofrojë faqja juaj që mysafirët të vijnë drejtpërdrejt te ju.","../wissen-direktbuchungen.html")],
"wis_lesen": "Lexo",

"zitat": "Këshillim, jo imponim. Jam gjithmonë i hapur për një bisedë pa detyrim.",
"zitat_quelle": "Kastriot Tafolli · TB Solutions",

"cta_tag": "// hapi tjetër",
"cta_h2": [["Le të flasim për biznesin tuaj."]],
"cta_text": "Biseda e parë zgjat gjysmë ore dhe nuk ju detyron me asgjë. Pas saj e dini nëse dhe ku mund t'ju ndihmoj.",
"cta_1": "Cakto një bisedë", "cta_2": "Hap llogaritësit",

"foot_text": "Drejtim gastronomie, digjitalizim, automatizim me IA dhe sisteme IA për hoteleri dhe gastronomi.",
"foot_status": "TB SOLUTIONS · ONLINE",
"foot_sp1": "Faqet",
"foot_l1": [("../ueber-mich.html","Rreth meje"),("../werdegang.html","Karriera"),("../leistungen.html","Shërbimet"),
            ("../teamo-ki.html","TeamO IA"),("../rechner.html","Llogaritësit"),("../wissen.html","Njohuri"),
            ("../referenzen.html","Referenca"),("../kontakt.html","Kontakt")],
"foot_sp2": "Fushat",
"foot_l2": [("../fb-beratung.html","Konsulencë F&B"),("../online-marketing.html","Marketing online dhe web"),
            ("../kontakt.html","Automatizim me IA"),("../teamo-ki.html","Sisteme IA"),("../rechner.html","Llogaritësit")],
"foot_sp3": "Kontakt",
"foot_adresse": ["Hauptstraße 1, 18609 Ostseebad Binz, Gjermani","Schluchsee, Pylli i Zi"],
"foot_copy": "© 2026 Kastriot Tafolli · tafolli.net · Rügen / Schluchsee",
"foot_impressum": "Impressum", "foot_datenschutz": "Privatësia",
"foot_shell": "$ hoteleri --digjitale --ia",
}
