# -*- coding: utf-8 -*-
"""Deutscher Originalinhalt. Quelle der Wahrheit, EN und SQ sind Uebersetzungen."""

DE = {
"code": "de", "dir": "", "name": "Deutsch", "locale": "de_DE",
"titel": "Kastriot Tafolli · Gastronomie, Digitalisierung und Künstliche Intelligenz",
"beschreibung": "Fünfzehn Jahre Führung in der 5-Sterne-Hotellerie, verbunden mit einer Ausbildung zum Softwareingenieur. F&B-Beratung, Online-Marketing, KI-Automatisierung und KI-Lösungen für Hotels und Restaurants.",

"nav": [("ueber-mich.html","Über mich"),("werdegang.html","Werdegang"),("leistungen.html","Leistungen"),("teamo-ki.html","TeamO KI"),("rechner.html","Rechner"),("wissen.html","Wissen"),("kontakt.html","Kontakt")],
"cta_nav": "Gespräch",
"skip": "Zum Inhalt springen",
"menu_auf": "Menü öffnen",

"hero_status": "Verfügbar für Beratung",
"hero_orte": ["Ostseebad Rügen 54.4°N", "Schluchsee 47.8°N"],
"hero_h1": [["Fünf Sterne","im Service."],["Eine Zeile","im Code."]],
"hero_text": "Ich bin Kastriot Tafolli. Fünfzehn Jahre Führung in der 5-Sterne-Hotellerie und eine Ausbildung zum Softwareingenieur mit Schwerpunkt Künstliche Intelligenz. Ich bringe Häuser operativ in Form und baue die Systeme, die ihnen danach Arbeit abnehmen.",
"hero_cta1": "Beratungsgespräch", "hero_cta2": "Ersparnis berechnen",

"term_titel": "tafolli@rügen ~ %",
"term": ["$ whoami","kastriot tafolli / f&b direktor + software engineer",
         "$ cat schwerpunkte.txt","01 gastronomische leitung, 5 sterne plus",
         "02 einkauf, vertraege, rueckverguetungen","03 websites, seo, kampagnen",
         "04 ki-automatisierung und eigene software","$ ./teamo --status",
         "● online / 24 h / mehrsprachig"],

"stats": [("200","+","geführte Mitarbeitende, gleichzeitig"),
          ("50","+","ausgebildete Nachwuchskräfte"),
          ("15","+","Jahre 5-Sterne-Gastronomie"),
          ("4","+","Hotels zeitgleich geleitet")],
"sprachen_label": "Sprachen", "sprachen_wert": "DE · EN · SQ", "sprachen_stufe": "C2 / C1 / NATIV",

"haeuser": ["Grand Hotel Binz","Cerês am Meer","Vier Jahreszeiten Binz","Rösing Touristik",
            "Raulff-Hotels","Vier Jahreszeiten am Schluchsee","Hotel Panorama Lohme",
            "Restaurant Wochenmarkt","Bukowina","Salsa Latino"],

"pos_tag": "Zwei Sprachen, ein Kopf",
"pos_h2": [["Diese Kombination gibt es"],["in der Branche kaum."]],
"pos_text": "Es gibt Hoteliers, die keine Zeile Code schreiben. Und es gibt Agenturen, die noch nie einen Dienstplan gemacht haben. Ich stehe dazwischen, und genau daraus entsteht der Unterschied.",
"pos_a_tag": "// im haus", "pos_a_h3": "Gastfreundschaft ist Handwerk.",
"pos_a_text": "Sie entsteht nicht aus Leitbildern, sondern aus hundert Kleinigkeiten, die jeden Abend stimmen müssen. Ich habe am Pass gestanden, Dienstpläne geschrieben, Inventuren gemacht und Sterne-Service verantwortet.",
"pos_a_chips": ["Flambieren","Bankett","Michelin-Stern","Halbpension","Dienstplan","Inventur","Wareneinsatz","Sommelier"],
"pos_b_tag": "// im code", "pos_b_h3": "Und Software ist auch Handwerk.",
"pos_b_text": "Ich habe programmieren gelernt, weil ich jeden Tag gesehen habe, wie viel Arbeitszeit in Häusern verbrennt, die eine Maschine übernehmen könnte. Heute baue ich genau diese Maschinen.",

"ki_tag": "KI-Automatisierung & KI-Management",
"ki_h2": [["Maschinen, die arbeiten."],["Menschen, die sie führen."]],
"ki_lede": "Automatisierung ohne Aufsicht ist ein Risiko, keine Lösung. Ich baue beides: die KI, die die Arbeit übernimmt, und die Struktur, die dafür sorgt, dass sie es weiterhin richtig tut.",
"ki_flip_label": "Automatisiert:",
"ki_flip_woerter": ["Anrufe.", "Rechnungen.", "Berichte.", "Antworten.", "Reservierungen.", "Daten."],

"ki_pipeline": [
  ("Eingang", "Anruf, Mail, Formular, Dokument"),
  ("Verstehen", "Inhalt einordnen, Absicht erkennen"),
  ("Handeln", "Antworten, eintragen, weiterleiten"),
  ("Prüfen", "Jede Ausgabe gegen Regeln kontrollieren"),
  ("Ausgang", "Ergebnis beim Empfänger, Protokoll bei mir"),
],

"ki_a_tag": "// Automatisierung", "ki_a_h3": "Was eine Maschine übernimmt.",
"ki_a_text": "Alles, was nach einem festen Muster abläuft: Anfragen beantworten, Daten aus Dokumenten ziehen, Einträge pflegen, Berichte zusammenstellen. Die KI arbeitet rund um die Uhr, ohne Pause und ohne Qualitätsschwankung.",
"ki_b_tag": "// Management", "ki_b_h3": "Was danach noch zu tun bleibt.",
"ki_b_text": "Ein System, das einmal läuft, läuft nicht von allein weiter. Prompts veralten, Kosten laufen aus dem Ruder, Antworten driften ab. Ich übernehme die laufende Pflege: prüfen, nachschärfen, eingreifen, wenn etwas nicht passt.",

"ki_showcase": [
  ("01", "Telefon & Chat", "Anrufe annehmen, Fragen beantworten, Gespräche in mehreren Sprachen führen."),
  ("02", "Dokumente", "Rechnungen, Verträge und Formulare auslesen und automatisch einordnen."),
  ("03", "E-Mail-Posteingang", "Nachrichten sortieren, Standardantworten verschicken, Dringendes markieren."),
  ("04", "Berichte", "Tagesabschlüsse, Auswertungen und Kennzahlen automatisch zusammenstellen."),
  ("05", "Reservierungen", "Buchungen prüfen, bestätigen und in bestehende Systeme eintragen."),
  ("06", "Daten-Abgleich", "Systeme synchron halten, Dubletten erkennen, Lücken schließen."),
  ("07", "Qualitätsprüfung", "Jede Ausgabe läuft vor dem Versand durch eine Kontrolle."),
],

"ki_vgl_tag": "Vorher / Nachher",
"ki_vgl_h3": "Der Unterschied ist spürbar, nicht nur gemessen.",
"ki_vgl_ohne": "Ohne Automatisierung",
"ki_vgl_mit": "Mit KI-Automatisierung",
"ki_vgl_ohne_punkte": [
  "Jede Anfrage braucht einen Menschen, der sie liest",
  "Antwortzeit hängt von Verfügbarkeit ab",
  "Fehler fallen oft erst beim Kunden auf",
  "Wissen steckt im Kopf einzelner Mitarbeitender",
],
"ki_vgl_mit_punkte": [
  "Wiederkehrende Anfragen beantwortet die KI direkt",
  "Antwort in Sekunden, rund um die Uhr",
  "Jede Ausgabe wird vor dem Versand geprüft",
  "Wissen steckt im System, nicht nur im Kopf",
],

"ki_dash_tag": "Beispielhafte Ansicht",
"ki_dash_h3": "So sieht KI-Management in der Praxis aus.",
"ki_dash_text": "Ein Ausschnitt aus der Art, wie ich ein laufendes System begleite — täglich, nicht nur beim Start. Werte hier sind ein Beispiel, keine Live-Daten.",
"ki_dash_status": "Online",
"ki_dash": [
  ("Antworten heute", "180", ""),
  ("Manuell geprüft", "12", ""),
  ("Durchschnittliche Antwortzeit", "2", " s"),
],
"ki_dash_letzte": "Letzte Überprüfung: heute, 07:40 Uhr",
"ki_showcase_tag": "Beispiele aus der Praxis",
"ki_cta": "Automatisierung besprechen",
"ki_cta_teamo": "TeamO als Beispiel ansehen",

"felder_tag": "Leistungsfelder",
"felder_h2": [["Vier Felder,"],["eine Handschrift."]],
"felder_text": "Die meisten Häuser haben nicht ein Problem, sondern mehrere, die zusammenhängen: der Wareneinsatz stimmt nicht, die Sichtbarkeit fehlt, das Team ertrinkt in Anfragen und zu viel Arbeit läuft noch von Hand.",
"felder": [
  ("01","Operativ","F&B-Beratung",
   "Getränke- und Lieferverträge, Rückvergütungen, Marketingzuschüsse, Wareneinsatz und Abläufe, die im Tagesgeschäft tragen.",
   ["Verträge mit Brauereien und Lieferanten","Rückvergütungen, Boni und Zuschüsse",
    "Wareneinsatz, Kalkulation, Inventur","Externe F&B-Leitung auf Zeit"],
   "fb-beratung.html","F&B-Beratung"),
  ("02","Digital","Online-Marketing & Web",
   "Sichtbarkeit, die Direktbuchungen bringt statt Portalprovision: Website, Suchmaschinen, Kampagnen, Inhalte und Bilder.",
   ["Website und Webentwicklung","SEO und lokale Sichtbarkeit",
    "Google Ads und Social Media","Foto, Video und Drohne"],
   "online-marketing.html","Digitalleistungen"),
  ("03","Künstliche Intelligenz","TeamO, der digitale KI-Mitarbeiter",
   "TeamO nimmt Anrufe an, beantwortet Anfragen in mehreren Sprachen, pflegt Reservierungen und legt der Geschäftsführung morgens einen fertigen Tagesbericht hin. Das konkrete Produkt aus der KI-Automatisierung und dem KI-Management, die oben beschrieben sind.",
   ["Telefonate und Reservierungen rund um die Uhr","E-Mail, WhatsApp, Website-Chat und Social Media",
    "Tagesberichte, Auslastung und Umsatzübersicht","Individuell trainiert, datenschutzkonform angebunden"],
   "teamo-ki.html","TeamO kennenlernen"),
],

"rech_tag": "Rechner",
"rech_h2": [["Rechnen Sie nach,"],["bevor Sie mit mir reden."]],
"rech_text": "Vier Rechner, direkt im Browser: Was kostet Sie das Telefon? Wie viel Portalprovision zahlen Sie im Jahr? Was liegt in Ihrem Getränkevertrag? Und was bringt regelmäßiges Posten? Alle Annahmen sind offen gelegt.",
"rech_cta": "Zu den Rechnern",
"rech_titel": "Beispielrechnung",
"rech_zeilen": [("45 Anrufe + 70 Nachrichten täglich","230 Std./Monat"),
                ("davon durch KI übernommen","70 %"),
                ("900 Übernachtungen, 15 % Provision","129.195 €/Jahr"),
                ("180.000 € Getränkeeinkauf, 3 % statt 8 %","9.000 €/Jahr")],
"rech_summe_label": "Größenordnung pro Jahr", "rech_summe": "94.467 €",

"abl_tag": "Zusammenarbeit",
"abl_h2": [["Vom ersten Gespräch bis"],["zum messbaren Ergebnis."]],
"abl_text": "Kein Standardpaket, das über jedes Haus gestülpt wird. Ich sehe mir an, wo Sie stehen, und arbeite an dem, was den größten Unterschied macht.",
"abl": [("01","Kennenlernen und Bestandsaufnahme","Ein unverbindliches Gespräch, telefonisch oder vor Ort. Ich höre zu, stelle Fragen zu Zahlen, Team und Abläufen und sage offen, ob ich der Richtige bin."),
        ("02","Analyse und Potenziale","Ich sehe mir Verträge, Wareneinsatz, Preisstruktur, Sichtbarkeit und Prozesse an und zeige, wo Geld liegen bleibt und wo Aufwand entsteht, der nicht sein muss."),
        ("03","Konzept und Priorisierung","Sie bekommen einen klaren Plan mit Maßnahmen, Reihenfolge, Aufwand und erwartetem Effekt. Was zuerst wirkt, kommt zuerst."),
        ("04","Umsetzung","Ich setze um, gemeinsam mit Ihrem Team und meinem Team von TB Solutions. Verhandlungen, Website, Kampagnen, Schulungen und Systeme aus einer Hand."),
        ("05","Kontrolle und Nachjustierung","Ergebnisse werden gemessen und nachgeschärft. Auf Wunsch begleite ich Ihr Haus dauerhaft oder übernehme die F&B-Leitung auf Zeit.")],

"wis_tag": "Wissen",
"wis_h2": [["Was ich aus der Praxis"],["aufgeschrieben habe."]],
"wis": [("Künstliche Intelligenz","Was ein KI-Mitarbeiter im Hotel wirklich übernimmt",
         "Zwischen Chatbot-Marketing und Betriebsrealität liegt ein weiter Weg. Was heute tatsächlich funktioniert, was nicht, und wo die Grenze verläuft.","wissen-ki-im-hotel.html"),
        ("Einkauf","Der Getränkevertrag, den niemand liest",
         "Rückvergütungen, Boni, Marketingzuschüsse und Verkaufsförderung. Wie diese Systeme funktionieren und warum die meisten Betriebe Geld liegen lassen.","wissen-getraenkevertrag.html"),
        ("Sichtbarkeit","Warum Ihre Gäste über ein Portal buchen",
         "Fünfzehn Prozent Provision sind kein Naturgesetz. Was eine eigene Website leisten muss, damit Gäste direkt bei Ihnen landen.","wissen-direktbuchungen.html")],
"wis_lesen": "Lesen",

"faq_tag": "Fragen",
"faq_h2": [["Was meistens zuerst"],["gefragt wird."]],
"faq": [
  ("Was kostet eine Automatisierung?",
   "Das hängt daran, wie viele Systeme angebunden werden müssen und wie viel Prüfung ein Vorgang braucht. Ein einzelner, klar umrissener Ablauf liegt deutlich unter einer durchgehenden Automatisierung über mehrere Abteilungen. Nach dem ersten Gespräch nenne ich eine Spanne, keinen Phantasiepreis."),
  ("Wie lange dauert es, bis etwas läuft?",
   "Der erste nutzbare Stand steht in Wochen, nicht in Monaten. Ich baue absichtlich zuerst den kleinsten Teil, der schon Arbeit abnimmt, und erweitere von dort — nicht ein halbes Jahr Entwicklung ohne Zwischenergebnis."),
  ("Bleiben die Daten im Haus?",
   "Wo es geht, ja. Was lokal verarbeitet werden kann, wird lokal verarbeitet. Wenn ein Sprachmodell eines Anbieters nötig ist, sage ich vorher offen, welche Daten es sieht, und die Verarbeitung wird nach DSGVO geregelt."),
  ("Was passiert, wenn die KI etwas falsch macht?",
   "Darum wird es herum gebaut, nicht erst hinterher gekümmert. Jede Ausgabe, die nach außen geht oder in ein System schreibt, bekommt eine Prüfung davor. Was unsicher ist, landet bei einem Menschen statt beim Kunden — das ist der Kern von KI-Management."),
  ("Was passiert, nachdem ein System läuft?",
   "Es wird beobachtet. Ich prüfe regelmäßig, ob die Antworten noch stimmen, ob sich Anfragen verändert haben, und schärfe nach, bevor aus einer kleinen Abweichung ein echtes Problem wird."),
  ("Brauche ich dafür ein eigenes Team?",
   "Nein. Genau das ist der Sinn von KI-Management als Dienstleistung: Sie bekommen ein laufendes System, ohne dass jemand bei Ihnen im Haus täglich danach schauen muss."),
  ("Arbeiten Sie auch an bestehendem Code?",
   "Ja. Bestehende Anwendungen erweitern, eine KI-Funktion in ein laufendes System einbauen oder einen Prototyp betriebsfest machen — das ist häufiger als ein Projekt von Null."),
],

"zitat": "Beratung, keine Bevormundung. Ich bin immer offen für ein unverbindliches Gespräch.",
"zitat_quelle": "Kastriot Tafolli · TB Solutions",

"cta_tag": "// nächster schritt",
"cta_h2": [["Reden wir über Ihr Haus."]],
"cta_text": "Ein Erstgespräch kostet eine halbe Stunde und ist unverbindlich. Danach wissen Sie, ob und wo ich Ihnen helfen kann.",
"cta_1": "Beratungsgespräch vereinbaren", "cta_2": "Rechner öffnen",

"foot_text": "Gastronomische Führung, Digitalisierung, KI-Automatisierung und KI-Lösungen für Hotellerie und Gastronomie.",
"foot_status": "TB SOLUTIONS · ONLINE",
"foot_sp1": "Seiten",
"foot_l1": [("ueber-mich.html","Über mich"),("werdegang.html","Werdegang"),("leistungen.html","Leistungen"),
            ("teamo-ki.html","TeamO KI"),("rechner.html","Rechner"),("wissen.html","Wissen"),
            ("referenzen.html","Referenzen"),("kontakt.html","Kontakt")],
"foot_sp2": "Schwerpunkte",
"foot_l2": [("fb-beratung.html","F&B-Beratung"),("online-marketing.html","Online-Marketing & Web"),
            ("#ki","KI-Automatisierung"),("teamo-ki.html","KI-Lösungen"),("rechner.html","Rechner")],
"foot_sp3": "Kontakt",
"foot_adresse": ["Hauptstraße 1, 18609 Ostseebad Binz","Schluchsee, Hochschwarzwald"],
"foot_copy": "© 2026 Kastriot Tafolli · tafolli.net · Ostseebad Rügen / Schluchsee",
"foot_impressum": "Impressum", "foot_datenschutz": "Datenschutz",
"foot_shell": "$ gastronomie --digital --ki",
}
