"""Editorial service catalogue. Each topic has its own substantial, linked page."""
import html, json
from bausteine import seite_rahmen, cta_block

SERVICES=[]
def add(slug,title,group,lead,problem,approach,modules,example,outputs,faq,related):
    SERVICES.append(dict(slug=slug,title=title,group=group,lead=lead,problem=problem,approach=approach,modules=modules,example=example,outputs=outputs,faq=faq,related=related))

add('digitalisierung','Digitalisierung','Technologie',
'Ein digitaler Betrieb beginnt mit Abläufen, die zusammenpassen. Ich verbinde die Erfahrung aus dem Hotelalltag mit der technischen Umsetzung.',
'Eine Reservierung steht im PMS, die Veranstaltungsdetails liegen in einer E-Mail und der Dienstplan lebt in einer Tabelle. Sobald Informationen mehrfach gepflegt werden, entstehen Rückfragen, Fehler und unnötige Handgriffe. Digitalisierung soll diesen Alltag vereinfachen und Ihrem Team eine verlässliche Grundlage geben.',
'Ich nehme zunächst einen konkreten Ablauf auf: Wer benötigt welche Information, wann und in welchem System? Gemeinsam legen wir fest, welche Schritte bleiben, welche entfallen und wo eine technische Verbindung sinnvoll ist. Erst danach wählen wir Software und Schnittstellen aus.',
[('Systemlandschaft verstehen','Hotelsoftware, Kassensystem, Warenwirtschaft und Kommunikation werden als zusammenhängender Ablauf betrachtet. Datenquellen, Zuständigkeiten und doppelte Arbeit werden sichtbar.'),('Werkzeuge verbinden','Schnittstellen oder strukturierte Importe übertragen Informationen zwischen den vereinbarten Systemen. Wo eine direkte Anbindung fehlt, planen wir einen nachvollziehbaren Übergang statt einer fragilen Abkürzung.'),('Menschen mitnehmen','Neue Abläufe werden mit den Mitarbeitenden erprobt und dokumentiert. Schulung, Verantwortlichkeiten und Rückmeldungen gehören zur Einführung ebenso wie die Technik.')],
'Bei einer Veranstaltungsanfrage werden Informationen einmal strukturiert erfasst. Angebot, interne Abstimmung und Checkliste greifen auf dieselbe Grundlage zu; Änderungen müssen nicht in mehreren Dokumenten nachgetragen werden.',
['Übersicht Ihrer Systeme und Datenwege','Priorisierte Liste sinnvoller Verbesserungen','Ein abgegrenzter erster digitaler Ablauf','Dokumentation, Übergabe und vereinbarte Betreuung'],
[('Müssen wir unsere Hotelsoftware ersetzen?','Oft lässt sich mit vorhandenen Werkzeugen anfangen. Ein Wechsel wird erst sinnvoll, wenn konkrete Anforderungen mit dem bisherigen System nicht zuverlässig erfüllt werden können.'),('Wo beginnt ein kleiner Betrieb?','Bei einem häufigen und klar begrenzten Problem, etwa Veranstaltungsanfragen, Bestellungen oder täglichen Berichten. Ein funktionierender erster Ablauf schafft eine bessere Grundlage als ein großes unübersichtliches Projekt.')],
['softwareentwicklung','ki-entwicklung','ki-automatisierung'])

add('cybersecurity','Cybersecurity & IT-Sicherheit','Technologie',
'Gästedaten, E-Mail und Zugänge verdienen dieselbe Aufmerksamkeit wie Ihr Service. Ich unterstütze die praktische Absicherung Ihrer digitalen Arbeitsumgebung.',
'Gemeinsame Passwörter, alte Benutzerkonten oder ein Backup, das noch nie wiederhergestellt wurde: Sicherheitsprobleme beginnen häufig bei alltäglichen Gewohnheiten. In Hotels und Restaurants arbeiten wechselnde Teams mit sensiblen Informationen und vielen externen Dienstleistern. Klar geregelte Zugriffe reduzieren vermeidbare Risiken.',
'Wir erfassen die vereinbarten Systeme, Zugänge und Zuständigkeiten. Darauf folgt eine nach Dringlichkeit geordnete Maßnahmenliste. Ich unterstütze die Umsetzung grundlegender Schutzmaßnahmen und beziehe für spezialisierte Prüfungen die zuständigen IT-Partner ein. Der Umfang wird vorab festgelegt.',
[('Zugänge und Rollen','Persönliche Konten, Mehrfaktor-Anmeldung und nachvollziehbare Berechtigungen ersetzen geteilte Zugänge. Für Eintritte, Rollenwechsel und Austritte entstehen einfache Checklisten.'),('Website und E-Mail','Updates, sichere Konfiguration und die Zuständigkeit für Wartung werden geprüft. Für E-Mail werden vorhandene Schutzfunktionen und die Authentifizierung der Absenderdomain gemeinsam mit dem Anbieter eingerichtet.'),('Backup und Wiederanlauf','Wir klären, welche Daten gesichert werden, wer die Sicherungen überwacht und wie eine Wiederherstellung abläuft. Ein dokumentierter Test zeigt, ob der vereinbarte Wiederanlauf praktisch funktioniert.')],
'Eine ehemalige Mitarbeiterin soll keinen Zugriff mehr auf Reservierung, E-Mail oder Social Media haben. Eine zentrale Austrittscheckliste stellt sicher, dass Zugänge deaktiviert, geteilte Geheimnisse geändert und Verantwortlichkeiten bestätigt werden.',
['Bestandsaufnahme im vereinbarten Umfang','Priorisierte technische und organisatorische Maßnahmen','Dokumentierte Rollen und Zugangsprozesse','Backup- und Wiederherstellungsablauf'],
[('Ist das ein Penetrationstest?','Ein Angriffstest oder eine formale Zertifizierung ist kein Bestandteil der grundlegenden Absicherung. Wenn ein solcher Test gebraucht wird, legen wir ihn als eigenen Auftrag mit einem geeigneten Spezialisten fest.'),('Können Sie absolute Sicherheit versprechen?','Nein. Ziel ist, konkrete Risiken zu reduzieren und klare Abläufe für Wartung, Zugriffe und Störungen zu schaffen. Welche Systeme und Maßnahmen dazugehören, steht im Angebot.')],
['domain-hosting-email','digitalisierung','softwareentwicklung'])

add('ki-entwicklung','KI-Entwicklung & KI-Assistenten','Technologie',
'KI wird nützlich, wenn sie Ihren Betrieb versteht. Ich entwickle Assistenten für konkrete Aufgaben, mit ausgewählten Wissensquellen und klaren Grenzen.',
'Ein allgemeiner Chatbot kennt weder Ihre Hausregeln noch den aktuellen Ablauf einer Veranstaltung. Ohne passende Informationen entstehen Antworten, die überzeugend klingen, aber nicht zum Betrieb passen. Gute KI-Entwicklung beginnt deshalb mit einer präzisen Aufgabe und einem verlässlichen Wissensbestand.',
'Wir definieren Nutzer, Fragen und gewünschte Ergebnisse. Ich strukturiere die geeigneten Quellen, entwickle die technische Anbindung und prüfe Antworten anhand typischer sowie schwieriger Fälle. Informationen, die fehlen oder widersprüchlich sind, sollen sichtbar werden und an einen Menschen weitergegeben werden.',
[('Wissen nutzbar machen','Hausinformationen, interne Anleitungen und freigegebene Dokumente werden geordnet. Der Assistent erhält nur Zugriff auf die Quellen und Funktionen, die für seine Aufgabe benötigt werden.'),('Antworten und Aktionen trennen','Ein Antwortentwurf braucht andere Rechte als eine Buchungsänderung. Wir legen fest, was die KI vorschlagen darf und welche Aktionen eine ausdrückliche Freigabe benötigen.'),('Qualität laufend prüfen','Beispielfragen, Quellenbezug und festgelegte Kriterien machen die Qualität überprüfbar. Rückmeldungen aus dem Betrieb helfen, Inhalte und Regeln gezielt zu verbessern.')],
'Ein interner Assistent beantwortet Fragen zum Bankettstandard anhand freigegebener Anleitungen. Findet er keine passende Quelle, markiert er die Lücke und nennt die zuständige Person, statt einen Ablauf zu erfinden.',
['Aufgabenbeschreibung und Wissensstruktur','Prototyp mit ausgewählten Quellen','Prüffälle und dokumentierte Grenzen','Anbindung, Einführung und Betreuung nach Vereinbarung'],
[('Trainieren Sie ein eigenes großes Sprachmodell?','Für viele Aufgaben ist ein bestehendes Modell mit passenden Wissensquellen und Regeln sinnvoller. Ob zusätzliche Anpassungen notwendig sind, entscheidet sich anhand der Aufgabe und der Tests.'),('Was passiert mit sensiblen Daten?','Vor der Umsetzung legen wir fest, welche Daten überhaupt benötigt werden, wer darauf zugreifen darf und welcher Anbieter geeignet ist. Die Datenverarbeitung wird als konkrete Projektanforderung behandelt.')],
['ki-automatisierung','teamo-ki','softwareentwicklung'])

add('softwareentwicklung','Softwareentwicklung','Technologie',
'Wenn Standardsoftware Ihren Ablauf nicht abbildet, entsteht eine Lösung nach Maß. Für Daten, Schnittstellen und die Arbeit hinter den Kulissen.',
'Viele Betriebe wachsen um ihre Software herum: zusätzliche Tabellen, manuelle Exporte und kleine Hilfslösungen übernehmen immer mehr wichtige Aufgaben. Irgendwann fehlt die Übersicht, welche Zahl aktuell ist oder warum eine Übertragung scheitert. Individuelle Software kann diese Lücken gezielt schließen.',
'Ich übersetze den betrieblichen Bedarf in einen klar abgegrenzten Funktionsumfang. Datenmodell, Zugriffsrechte und Schnittstellen werden vor der Entwicklung festgelegt. Die Lösung wird mit repräsentativen Fällen geprüft und so übergeben, dass Betrieb, Wartung und Weiterentwicklung nachvollziehbar bleiben.',
[('Datenbanken und Schnittstellen','Python, JavaScript und SQL helfen, Daten strukturiert zu verarbeiten und vorhandene Systeme zu verbinden. Die konkrete Technik richtet sich nach Anforderungen, Schnittstellen und dem späteren Betrieb.'),('Interne Werkzeuge','Dashboards, Freigaben oder kleine Fachanwendungen ersetzen wiederholte Handarbeit. Die Oberfläche zeigt genau die Informationen, die eine bestimmte Rolle für ihre Entscheidungen braucht.'),('Betrieb und Wartung','Fehlerbehandlung, Protokollierung und eine klare Übergabe gehören zur Entwicklung. Für Änderungen und Aktualisierungen vereinbaren wir Zuständigkeiten und einen passenden Betreuungsumfang.')],
'Ein täglicher Bericht führt freigegebene Kassen- und Umsatzdaten zusammen. Fehlende Exporte werden markiert, statt als Nullumsatz in die Auswertung einzugehen; das Team kann Abweichungen gezielt prüfen.',
['Abgestimmter Funktionsumfang','Implementierung und vereinbarte Schnittstellen','Prüfung wichtiger Geschäftsabläufe','Dokumentation und technische Übergabe'],
[('Individuell entwickeln oder Standardsoftware kaufen?','Wenn eine vorhandene Lösung den Bedarf gut erfüllt, ist sie häufig der bessere Start. Eine eigene Entwicklung lohnt sich bei konkreten Lücken oder Abläufen, die sich damit deutlich vereinfachen lassen.'),('Kann eine vorhandene Anwendung erweitert werden?','Ja, sofern der Quellcode oder die nötigen Schnittstellen verfügbar sind. Zuerst prüfe ich die technische Grundlage und den Aufwand einer Erweiterung.')],
['app-entwicklung','digitalisierung','ki-entwicklung'])

add('app-entwicklung','App- & Web-App-Entwicklung','Technologie',
'Checklisten, Bestellungen und Freigaben dort erledigen, wo die Arbeit stattfindet. Individuelle Anwendungen für Ihr Team und Ihre Gäste.',
'Eine Papierliste lässt sich schnell ausfüllen, aber nur schwer über mehrere Schichten auswerten. Eine Tabelle am Bürocomputer hilft wenig, wenn die Bestellung im Restaurant aufgenommen werden muss. Eine passende Web-App bringt den Ablauf auf die Geräte, die Ihr Team tatsächlich nutzt.',
'Wir legen die wichtigsten Nutzerwege fest und erproben eine erste Oberfläche mit echten Anwendern. Danach folgen Funktionen, Rollen und die Verbindung zu vorhandenen Daten. Browserbasierte Anwendungen sind häufig ein sinnvoller Einstieg; native Apps werden anhand des tatsächlichen Bedarfs bewertet.',
[('Mobile Abläufe','Formulare und Ansichten werden für kleine Bildschirme und schnelle Bedienung gestaltet. Wichtige Pflichtangaben, klare Rückmeldungen und wenige Schritte reduzieren Fehler im Tagesgeschäft.'),('Freigaben und Übersicht','Bestellungen oder Aufgaben bekommen einen nachvollziehbaren Status. Zuständige Personen sehen offene Vorgänge, ohne in mehreren Chatgruppen nachfragen zu müssen.'),('Anbindung und Rechte','Die Anwendung verwendet vereinbarte Datenquellen und klar definierte Rollen. Wer etwas lesen, ändern oder freigeben darf, wird im Ablauf berücksichtigt.')],
'Die Restaurantleitung meldet eine Bestellung per Smartphone. Der Einkauf prüft die Angaben, gibt sie frei und dokumentiert den Status; Rückfragen bleiben am Vorgang sichtbar.',
['Nutzerwege und erster Oberflächenentwurf','Anwendung mit abgestimmten Funktionen','Rollen und Statusmodell','Einführung mit Anwenderfeedback'],
[('Muss jeder eine App installieren?','Eine Web-App kann im Browser genutzt werden. Ob eine Installation, Offline-Funktion oder native Anwendung erforderlich ist, klären wir anhand der Arbeitssituation.'),('Geht das auch für einen kleinen Betrieb?','Ja. Ein klar begrenztes Werkzeug für einen häufigen Ablauf ist oft sinnvoller als eine große Anwendung mit vielen selten genutzten Funktionen.')],
['softwareentwicklung','digitalisierung','personal-recruiting'])

add('webdesign','Webdesign & Webentwicklung','Digitaler Auftritt',
'Ein Hotelauftritt darf begeistern und muss den nächsten Schritt einfach machen. Ich entwickle Websites mit Persönlichkeit, klarer Struktur und echter Buchungsnähe.',
'Gäste wollen Atmosphäre erleben und zugleich konkrete Antworten finden: Zimmer, Küche, Lage, Preise und Buchung. Wenn die Website diese Informationen versteckt oder auf dem Smartphone schwer zu bedienen ist, verlieren selbst schöne Bilder ihre Wirkung. Gestaltung und Nutzbarkeit müssen zusammenarbeiten.',
'Wir strukturieren Angebote und Zielgruppen, schreiben passende Inhalte und entwickeln ein visuelles Konzept. Animationen unterstützen die Geschichte Ihres Hauses. Buchungsstrecke, Kontakt und mobile Bedienung werden früh mitgedacht und vor dem Start geprüft.',
[('Gestaltung mit Charakter','Typografie, Bildsprache und Bewegung bilden einen zusammenhängenden Auftritt. Das Design wird aus Ihrem Haus entwickelt und bleibt auch ohne Animation verständlich.'),('Technische Umsetzung','Responsive Seiten, verständliche Navigation und schlanke Medien unterstützen die Nutzung auf unterschiedlichen Geräten. Bestehende Buchungsanbieter werden im vereinbarten Umfang eingebunden.'),('Inhalte und Auffindbarkeit','Eigene Seiten für Angebote, Zimmer oder Veranstaltungen beantworten konkrete Suchfragen. Titel, Beschreibungen und interne Links geben Menschen und Suchmaschinen Orientierung.')],
'Eine Restaurantseite zeigt Atmosphäre, aktuelle Speisekarte, Öffnungszeiten und Reservierung an einem Ort. Wer über die Suche auf eine Veranstaltung gelangt, findet direkt die passende Anfrage statt nur die allgemeine Startseite.',
['Seitenstruktur und visuelles Konzept','Responsive Umsetzung mit individuellen Inhalten','Buchungs- oder Kontaktanbindung','Prüfung und Einführung vor dem Start'],
[('Kann meine vorhandene Website modernisiert werden?','Ja. Inhalte, bestehende Adressen und benötigte Anbindungen werden zuerst aufgenommen. So kann die Modernisierung auf einer verlässlichen Grundlage erfolgen.'),('Wer aktualisiert später Karten und Angebote?','Das kann Ihr Team oder ich übernehmen. Die passende Lösung und die Zuständigkeit für laufende Änderungen werden vor dem Projekt festgelegt.')],
['suchmaschinenoptimierung','domain-hosting-email','foto-video'])

add('suchmaschinenoptimierung','Suchmaschinenoptimierung & lokale Sichtbarkeit','Digitaler Auftritt',
'Gefunden werden, wenn ein Gast genau Ihr Angebot sucht. SEO für Hotels und Restaurants verbindet Technik, Inhalte und lokale Relevanz.',
'Eine Website kann viele Seiten haben und trotzdem die wichtigsten Fragen unbeantwortet lassen. Suchende möchten wissen, ob Ihr Haus zu ihrem Anlass passt: Familienurlaub, Dinner, Tagung oder ein Wochenende in Ihrer Region. Dafür brauchen sie hilfreiche Informationen und eindeutige Einstiegsseiten.',
'Ich prüfe vorhandene Seiten, Suchfragen und technische Hindernisse. Daraus entsteht eine priorisierte Inhalts- und Maßnahmenplanung. Wir verbessern zunächst die Seiten mit dem größten Bezug zu Ihrem Angebot und beobachten anschließend, welche Suchanfragen und Kontakte daraus entstehen.',
[('Technische Grundlage','Indexierbarkeit, Seitentitel, interne Links und mobile Nutzbarkeit werden geprüft. Beim Umbau bestehender Websites werden bisherige URLs und nötige Weiterleitungen berücksichtigt.'),('Hilfreiche Angebotsseiten','Jede wichtige Leistung oder Gästegruppe erhält passende Informationen. Inhalte beantworten konkrete Fragen, statt nur Suchbegriffe zu wiederholen.'),('Lokale Auffindbarkeit','Hausdaten, Öffnungszeiten und regionale Inhalte werden konsistent aufbereitet. Vorhandene Unternehmensprofile und deren Verbindung zur Website fließen in die Bestandsaufnahme ein.')],
'Ein Hotel mit Tagungsangebot bekommt eine eigene Seite mit Raumgrößen, Möglichkeiten, Anreise und Anfrageweg. So finden Veranstaltungsplaner die relevanten Informationen auch ohne die gesamte Website zu durchsuchen.',
['Bestandsaufnahme von Technik und Inhalten','Plan für relevante Suchfragen und Angebotsseiten','Umsetzung priorisierter Verbesserungen','Auswertung anhand vereinbarter Kennzahlen'],
[('Ist mehr Text automatisch besser?','Nein. Ein Text hilft, wenn er eine echte Frage beantwortet und zum Angebot passt. Zusätzliche Seiten brauchen einen eigenen Zweck und sollten sich inhaltlich unterscheiden.'),('Garantieren Sie Platz eins?','Nein. Sichtbarkeit hängt von Wettbewerb, Suchanfrage und vielen weiteren Faktoren ab. Vereinbart werden konkrete Maßnahmen und nachvollziehbare Kennzahlen.')],
['webdesign','online-marketing','social-media'])

add('domain-hosting-email','Domain, Hosting & E-Mail','Digitaler Auftritt',
'Eine verlässliche Basis für Ihren digitalen Auftritt: eigene Domain, betreute Website und professionelle E-Mail-Adressen.',
'Wenn eine Domain auf den früheren Dienstleister läuft oder niemand die Zugangsdaten kennt, wird selbst eine kleine Änderung schwierig. Website, E-Mail und DNS müssen nachvollziehbar verwaltet werden. Klare Zuständigkeiten verhindern, dass der Betrieb bei einem Wechsel den Überblick verliert.',
'Ich prüfe Anbieter, Eigentümerschaft, Zugänge und die benötigten Funktionen. Danach planen wir Einrichtung oder Umzug mit Blick auf Website und E-Mail. Wartung, Sicherungen und Ansprechpartner werden dokumentiert, damit die technische Grundlage langfristig handhabbar bleibt.',
[('Domain und DNS','Die Domain wird dem richtigen Inhaber zugeordnet; relevante Einträge werden dokumentiert. Änderungen werden mit den beteiligten Anbietern abgestimmt.'),('Hosting und Wartung','Ein geeigneter Hostingumfang richtet sich nach der Website und den eingesetzten Anwendungen. Updates, Sicherungen und Zuständigkeiten werden ausdrücklich vereinbart.'),('E-Mail im Betrieb','Persönliche Postfächer, Funktionsadressen und Zugriffsregeln erhalten eine klare Struktur. Bei einem Umzug prüfen wir die benötigten Nachrichten, Geräte und Übergangsabläufe.')],
'Eine neue Restaurantleitung übernimmt den Betrieb. Domain und Postfächer werden mit dokumentierten Zugängen übergeben; allgemeine Anfragen gehen an eine Funktionsadresse und hängen nicht am Konto einer einzelnen Person.',
['Anbieter- und Zugangsübersicht','Einrichtung oder abgestimmter Umzugsplan','Dokumentierte Domain- und Postfachstruktur','Betreuung mit festgelegtem Umfang'],
[('Kann die bestehende Domain bleiben?','Ja. Häufig ändern sich nur Anbieter oder Verwaltung. Vor einer Änderung wird geprüft, wie die Domain aktuell mit Website und E-Mail verbunden ist.'),('Ist laufende Betreuung enthalten?','Der Betreuungsumfang wird im Angebot beschrieben. Dazu können Wartung, Sicherungen und Unterstützung bei Änderungen gehören; er wird auf Ihren Bedarf abgestimmt.')],
['cybersecurity','webdesign','digitalisierung'])

add('social-media','Social Media & Content','Digitaler Auftritt',
'Zeigen, was Ihr Haus besonders macht. Mit Inhalten, die zu Ihrem Betrieb passen und einen klaren Weg zur Anfrage bieten.',
'Zwischen Service, Einkauf und Personal bleibt wenig Zeit für regelmäßige Beiträge. Spontane Posts zeigen einzelne Momente, ergeben aber selten eine erkennbare Geschichte. Ein durchdachter Plan verbindet Atmosphäre, Angebote und die Menschen hinter Ihrem Haus.',
'Wir klären Zielgruppen, Kanäle und die wichtigsten Themen. Daraus entstehen ein Redaktionsplan und wiederverwendbare Formate. Inhalte werden mit Ihrem Team abgestimmt, Freigaben organisiert und Ergebnisse anhand der tatsächlich relevanten Reaktionen ausgewertet.',
[('Themen und Planung','Saisonangebote, Kulinarik, Veranstaltungen und Teamgeschichten bilden einen planbaren Rhythmus. Die Frequenz richtet sich nach verfügbarer Qualität und Kapazität.'),('Beiträge und Reels','Text, Bild und kurze Videos werden für den jeweiligen Kanal gestaltet. Jeder Inhalt bekommt eine verständliche Aussage und bei Bedarf einen passenden Anfrageweg.'),('Betreuung und Auswertung','Kommentare, Zuständigkeiten und Freigaben werden geregelt. Neben Reichweite betrachten wir etwa Profilbesuche, Website-Klicks oder qualifizierte Anfragen.')],
'Ein saisonales Menü wird nicht nur einmal angekündigt: Ein Küchenmoment, die Geschichte einer Zutat und ein klarer Reservierungshinweis erzählen zusammen, warum sich ein Besuch lohnt.',
['Kanal- und Themenplanung','Abgestimmter Redaktionskalender','Gestaltete Beiträge und vereinbarte Formate','Auswertung und Anpassung der Inhalte'],
[('Müssen wir auf jedem Kanal aktiv sein?','Nein. Entscheidend ist, wo Ihre Gäste erreicht werden können und welche Inhalte Sie verlässlich bereitstellen können. Wenige gut betreute Kanäle können sinnvoller sein.'),('Können Mitarbeitende Inhalte zuliefern?','Ja. Ein einfacher Ablauf für Material, Einwilligungen und Freigaben hilft dabei, authentische Momente aus dem Alltag nutzbar zu machen.')],
['foto-video','online-marketing','webdesign'])

add('foto-video','Foto, Video & visuelle Inhalte','Digitaler Auftritt',
'Räume, Küche und Menschen so zeigen, dass Ihr Haus erlebbar wird. Visuelle Inhalte für Website, Kampagnen und soziale Kanäle.',
'Ein Bild kann zeigen, wie ein Zimmer aussieht. Eine durchdachte Bildserie zeigt, wie sich ein Aufenthalt anfühlt. Häufig fehlt Betrieben eine konsistente Auswahl für Website, Angebote und Social Media; vorhandenes Material passt weder zum Format noch zum aktuellen Auftritt.',
'Wir planen Motive, Einsatzorte und Formate vor dem Termin. Eine Aufnahmeplanung berücksichtigt den laufenden Betrieb, das Licht und beteiligte Personen. Produktion und Bearbeitung werden abgestimmt; besondere Aufnahmen wie Drohnenmaterial werden mit geeigneten Partnern und den erforderlichen Voraussetzungen geplant.',
[('Bildkonzept und Motive','Zimmer, Gastronomie, Details und Gastgeber bekommen eine gemeinsame Bildsprache. Eine Motivliste hilft, wichtige Angebote vollständig abzubilden.'),('Formate für den Einsatz','Website benötigt andere Ausschnitte als ein Reel oder eine Anzeige. Die benötigten Varianten werden von Beginn an berücksichtigt.'),('Auswahl und Übergabe','Das Material wird für die vereinbarten Kanäle geordnet und passend aufbereitet. Nutzungsumfang, Freigaben und Übergabeformate werden vorab geklärt.')],
'Für ein neues Dinnerangebot entstehen ein starkes Titelbild, Detailaufnahmen und kurze vertikale Sequenzen. Website und soziale Kanäle erzählen dieselbe Geschichte, ohne dass jedes Motiv neu produziert werden muss.',
['Motivliste und Aufnahmeplanung','Abgestimmte Foto- und Videoformate','Bearbeitete Auswahl für vereinbarte Kanäle','Geordnete Übergabe mit Nutzungsumfang'],
[('Ist ein großer Produktionstag nötig?','Nicht immer. Je nach Ziel können ein begrenzter Termin oder mehrere kleinere Einheiten sinnvoll sein. Die Planung richtet sich nach benötigtem Material und Betrieb.'),('Bieten Sie Drohnenaufnahmen an?','Drohnenmaterial kann projektbezogen geplant werden. Standort, Genehmigungen, geeignete Durchführung und Nutzungsumfang werden vor einer Zusage geklärt.')],
['webdesign','social-media','online-marketing'])

add('lieferantenvereinbarungen','Lieferantenvereinbarungen & Einkauf','F&B & Hospitality',
'Ein guter Einkauf endet nicht beim Stückpreis. Ich verbinde Bedarf, Lieferfähigkeit und nachvollziehbare Konditionen zu einer belastbaren Vereinbarung.',
'Ein scheinbar günstiger Preis kann durch Mindestmengen, Lieferkosten oder unpassende Gebinde relativiert werden. In der Hotellerie zählen zusätzlich Verfügbarkeit, Qualität und schnelle Reaktion bei Veranstaltungen. Lieferantenvereinbarungen müssen zum tatsächlichen Verbrauch und zum Alltag in Küche und Service passen.',
'Ich nehme Bedarf, vorhandene Lieferanten und Vereinbarungen auf. Angebote werden auf einer vergleichbaren Grundlage gegenübergestellt. Anschließend bereiten wir Verhandlung und Entscheidung vor; auf Wunsch begleite ich die Gespräche und dokumentiere die vereinbarten wirtschaftlichen Eckpunkte.',
[('Bedarf und Sortiment','Verbrauch, Qualität und Einsatz der Produkte werden gemeinsam mit dem Team betrachtet. So lässt sich erkennen, wo Bündelung hilft und wo Vielfalt für das Konzept wichtig bleibt.'),('Konditionen vergleichen','Preise, Fracht, Zahlungsziele, Mindestbestellungen und Rückvergütungen werden zusammen betrachtet. Ein Vergleich bewertet den realistischen Gesamtbezug statt isolierter Rabattzahlen.'),('Vereinbarungen nachhalten','Ansprechpartner, Laufzeiten und zugesagte Leistungen werden dokumentiert. Regelmäßige Abgleiche zeigen, ob Abrechnung und Lieferung der Vereinbarung entsprechen.')],
'Zwei Outlets bestellen ähnliche Produkte bei verschiedenen Lieferanten. Ein Vergleich prüft, ob eine gebündelte Beschaffung bessere Bedingungen bringt, ohne Qualität oder Lieferfähigkeit zu verschlechtern.',
['Bedarfs- und Lieferantenübersicht','Vergleich relevanter Gesamtkonditionen','Vorbereitung oder Begleitung der Verhandlung','Dokumentierte Vereinbarungen und Kontrollpunkte'],
[('Müssen wir den Lieferanten wechseln?','Nein. Oft lohnt zuerst ein strukturierter Abgleich und ein Gespräch mit dem bestehenden Partner. Ein Wechsel wird anhand von Qualität, Wirtschaftlichkeit und Zuverlässigkeit bewertet.'),('Ist das eine juristische Vertragsprüfung?','Im Mittelpunkt stehen betriebliche und wirtschaftliche Konditionen. Wenn eine rechtliche Prüfung notwendig ist, wird dafür eine entsprechend qualifizierte Beratung hinzugezogen.')],
['rueckverguetungen','getraenkevertraege','wareneinsatz-kalkulation'])

add('rueckverguetungen','Rückvergütungen, Boni & Jahresvereinbarungen','F&B & Hospitality',
'Was vereinbart wurde, soll auch nachvollziehbar ankommen. Ich mache Rückvergütungen und Bonusmodelle im Einkauf transparent.',
'Boni stehen manchmal in Nebenabreden, Jahresvereinbarungen oder wechselnden Abrechnungen. Mengenstaffeln, Produktgruppen und Fristen machen den Überblick schwierig. Ohne regelmäßigen Abgleich bleibt unklar, welche Beträge erwartet werden dürfen und welche Bedingungen bereits erfüllt sind.',
'Wir sammeln die relevanten Vereinbarungen und strukturieren die Berechnungsgrundlage. Bezugsdaten werden den Bedingungen gegenübergestellt. Daraus entsteht eine nachvollziehbare Übersicht für Abrechnung, Rückfragen und die nächste Verhandlungsrunde. Erwartete Beträge werden von tatsächlich bestätigten Gutschriften getrennt.',
[('Modelle sichtbar machen','Mengenboni, Umsatzstaffeln, Marketingzuschüsse und weitere vereinbarte Leistungen werden separat erfasst. Produktbezug, Zeitraum und Bedingungen bleiben nachvollziehbar.'),('Abrechnung abgleichen','Bezogene Mengen oder Nettoumsätze werden mit der vereinbarten Basis verglichen. Abweichungen und fehlende Gutschriften können gezielt beim Lieferanten geklärt werden.'),('Nächste Vereinbarung vorbereiten','Die tatsächliche Entwicklung liefert eine Grundlage für die kommende Jahresvereinbarung. Unrealistische Schwellen und unklare Bedingungen werden vor der Verhandlung sichtbar.')],
'Eine Jahresgutschrift fällt niedriger aus als erwartet. Der strukturierte Abgleich zeigt, welche Produktgruppen berücksichtigt wurden und ob die vereinbarte Mengenstaffel mit den Bezugsdaten übereinstimmt.',
['Übersicht aller relevanten Bonusvereinbarungen','Nachvollziehbare Berechnungsgrundlagen','Abgleich erwarteter und bestätigter Beträge','Fristen und Vorbereitung der Jahresgespräche'],
[('Wie hoch ist die mögliche Rückvergütung?','Das hängt von Ihren bestehenden Vereinbarungen, Bezugsvolumen und Produktgruppen ab. Eine belastbare Größenordnung ergibt sich erst aus dem Abgleich dieser Daten.'),('Ist eine Rückvergütung immer besser als ein günstigerer Preis?','Nein. Entscheidend sind die Gesamtkosten und die Bedingungen. Ein niedrigerer Bezugspreis kann wirtschaftlicher sein als ein hoher Bonus mit schwer erreichbarer Schwelle.')],
['lieferantenvereinbarungen','getraenkevertraege','rechner'])

add('getraenkevertraege','Getränkeverträge & Brauereivereinbarungen','F&B & Hospitality',
'Getränkeverträge prägen Kosten, Sortiment und Spielraum über Jahre. Ich unterstütze die wirtschaftliche Vorbereitung und Verhandlung.',
'Getränkepreise, Bezugspflichten, Ausstattung und Zuschüsse stehen oft in einem gemeinsamen Paket. Der sichtbare Vorteil am Anfang sagt wenig über die Gesamtkosten während der Laufzeit aus. Ein passender Vertrag muss Absatz, Gastronomiekonzept und betriebliche Entwicklung zusammen berücksichtigen.',
'Ich erfasse vorhandene Vereinbarungen, Absatzdaten und geplante Veränderungen. Alternativen werden auf einer vergleichbaren Basis gerechnet. So gehen Sie mit einer klaren Entscheidungsgrundlage in die Verhandlung; rechtliche Detailfragen werden bei Bedarf separat geprüft.',
[('Absatz und Sortiment','Tatsächliche Mengen, Gebinde und Verkaufspreise bilden die Grundlage. Geplante Änderungen im Outlet oder Konzept werden vor einer neuen Bindung berücksichtigt.'),('Gesamtkonditionen','Bezugspreise, Boni, Ausstattung, Zuschüsse und Laufzeit werden gemeinsam betrachtet. Wichtig ist, welche Leistung an welche Verpflichtung geknüpft ist.'),('Verhandlung und Nachhalten','Anforderungen und Verhandlungsspielräume werden vorbereitet. Vereinbarte wirtschaftliche Bedingungen werden dokumentiert und später mit der Abrechnung abgeglichen.')],
'Ein Restaurant erhält ein Angebot mit neuer Schankanlage und Zuschuss. Die Bewertung stellt Investition und laufende Bezugskonditionen über die geplante Laufzeit gegenüber und prüft, ob der erwartete Absatz zur Vereinbarung passt.',
['Bestandsaufnahme und Absatzübersicht','Vergleich der wirtschaftlichen Konditionen','Vorbereitete Verhandlungsposition','Abgestimmte Kontrollpunkte für die Laufzeit'],
[('Wann sollte eine neue Vereinbarung vorbereitet werden?','Mit ausreichend Vorlauf vor einem Vertragsende oder einer geplanten Veränderung. Bestehende Fristen und Verpflichtungen werden zuerst aufgenommen.'),('Kann ich einen Vertrag einfach kündigen?','Das hängt von der konkreten Vereinbarung ab. Rechtliche Fragen zu Kündigung, Bindung und Wirksamkeit müssen anhand des Vertrags gesondert geprüft werden.')],
['lieferantenvereinbarungen','rueckverguetungen','wissen-getraenkevertrag'])

add('wareneinsatz-kalkulation','Wareneinsatz & Kalkulation','F&B & Hospitality',
'Eine gute Karte überzeugt Gäste und trägt den Betrieb. Ich bringe Rezepturen, Einkauf und Verkaufspreise in eine nachvollziehbare Rechnung.',
'Ein Gericht verkauft sich gut und bringt trotzdem zu wenig Beitrag zum Ergebnis. Rezepturänderungen, steigende Einkaufspreise oder unklare Portionen verschieben die Kalkulation schleichend. Ohne klare Bezugsgrößen bleibt der Wareneinsatz eine Zahl, deren Ursachen niemand zuverlässig erklären kann.',
'Wir betrachten Rezepturen, Mengen, Einkaufspreise und Verkaufszahlen. Speisen und Getränke werden auf einer einheitlichen Basis kalkuliert. Anschließend prüfen wir gemeinsam, welche Änderungen wirtschaftlich und im Service sinnvoll sind, ohne das Konzept Ihres Hauses aus dem Blick zu verlieren.',
[('Rezepturen und Portionen','Mengen, Ausbeuten und Portionsstandards werden gemeinsam mit Küche und Bar geklärt. Eine dokumentierte Grundlage macht Änderungen und Preisentwicklungen sichtbar.'),('Deckungsbeiträge','Erlöse und relevante variable Kosten werden vergleichbar gegenübergestellt. Absolute Beiträge und Absatz zeigen mehr als eine isolierte Wareneinsatzquote.'),('Karte und Abläufe','Produktmix, Verkauf und Umsetzung werden zusammen betrachtet. Empfehlungen müssen zu Gästen, Einkauf und den Kapazitäten des Teams passen.')],
'Ein beliebtes Menü wird anhand seiner tatsächlichen Rezeptur und aktuellen Bezugspreise neu berechnet. Das Team kann beurteilen, ob Preis, Portion oder Beilage angepasst werden sollte und welche Wirkung zu erwarten ist.',
['Einheitliche Kalkulationsgrundlagen','Auswertung ausgewählter Speisen und Getränke','Priorisierte Maßnahmen für Karte und Einkauf','Kontrollrhythmus für Preis- und Rezepturänderungen'],
[('Welche Wareneinsatzquote ist richtig?','Das hängt unter anderem von Konzept, Sortiment und Preisniveau ab. Eine Zielquote wird mit den tatsächlichen Zahlen des Betriebs hergeleitet.'),('Muss dafür die gesamte Karte geändert werden?','Nein. Häufig beginnt die Arbeit mit häufig verkauften oder besonders kostenintensiven Positionen. Die Analyse zeigt, wo eine Änderung tatsächlich sinnvoll ist.')],
['inventur-warenwirtschaft','lieferantenvereinbarungen','revenue-controlling'])

add('inventur-warenwirtschaft','Inventur & Warenwirtschaft','F&B & Hospitality',
'Bestände, Verbrauch und Bestellung miteinander verbinden. Für weniger Überraschungen zwischen Lager, Küche und Monatsabschluss.',
'Unterschiedliche Zähleinheiten, offene Umbuchungen und ungeklärte Brüche machen Inventuren mühsam. Wenn die Grundlage ungenau ist, lassen sich Fehlmengen oder der tatsächliche Verbrauch nur schwer beurteilen. Eine verlässliche Warenwirtschaft braucht gemeinsame Regeln und einen Ablauf, der unter Zeitdruck funktioniert.',
'Ich nehme Lagerstruktur, Artikeldaten und die bestehenden Zählprozesse auf. Wir vereinheitlichen Einheiten und Verantwortlichkeiten und testen den Ablauf mit dem Team. Abweichungen werden anschließend gezielt untersucht, statt jede Inventur wieder von vorn zu erklären.',
[('Artikel und Einheiten','Gebinde, Zähleinheiten und Bewertung werden eindeutig festgelegt. Doppelte oder veraltete Artikel erschweren die Auswertung und werden bereinigt.'),('Inventur im Alltag','Zählbereiche, Zeitpunkte und Verantwortlichkeiten erhalten eine klare Struktur. Dokumentierte Umbuchungen und Bewegungen machen Bestandsänderungen nachvollziehbar.'),('Bestellung und Kontrolle','Mindestbestände und Bestellrhythmen richten sich nach Verbrauch, Lieferzeiten und Veranstaltungen. Auffällige Differenzen werden regelmäßig besprochen.')],
'Die Bar zählt Flaschen, während die Warenwirtschaft Liter erwartet. Nach der Vereinheitlichung der Zähleinheit lassen sich Bestände korrekt bewerten und vermeintliche Verbrauchsabweichungen auflösen.',
['Strukturierte Artikel- und Lagergrundlage','Dokumentierter Inventurablauf','Zuständigkeiten und Zähleinheiten','Auswertung und Bearbeitung von Abweichungen'],
[('Brauchen wir ein neues Warenwirtschaftssystem?','Nicht zwingend. Zuerst wird geprüft, ob vorhandene Software die benötigten Regeln und Auswertungen unterstützt. Gute Stammdaten bleiben auch bei einem Wechsel entscheidend.'),('Wie oft sollte gezählt werden?','Der sinnvolle Rhythmus hängt von Warengruppe, Verbrauch und Kontrollbedarf ab. Häufige Teilinventuren können eine vollständige Bestandsaufnahme ergänzen.')],
['wareneinsatz-kalkulation','digitalisierung','lieferantenvereinbarungen'])

add('interim-fb-management','Interim F&B-Management','F&B & Hospitality',
'Führung auf Zeit, wenn Ihr Betrieb Klarheit und Entlastung braucht. Operative Verantwortung mit vereinbartem Auftrag und sauberer Übergabe.',
'Eine vakante Führungsposition, ein neues Outlet oder eine Saison mit hoher Belastung kann ein Team schnell an seine Grenzen bringen. In solchen Phasen braucht es Entscheidungen, sichtbare Ansprechpartner und verlässliche Abläufe. Externe F&B-Leitung kann eine Lücke überbrücken und zugleich Strukturen verbessern.',
'Vor dem Einsatz legen wir Auftrag, Entscheidungsspielraum, Präsenz und Zielsetzung fest. Ich arbeite mit den bestehenden Führungskräften und dem Team an den priorisierten Aufgaben. Fortschritt und offene Punkte werden regelmäßig besprochen; die Übergabe wird von Anfang an mitgeplant.',
[('Operative Orientierung','Abläufe in Restaurant, Frühstück, Bar und Bankett werden gemeinsam betrachtet. Akute Engpässe und Verantwortlichkeiten bekommen zuerst eine klare Struktur.'),('Führung und Zahlen','Dienstplanung, Qualitätsstandards und relevante Kennzahlen werden in einen nutzbaren Arbeitsrhythmus gebracht. Entscheidungen werden mit den verantwortlichen Personen abgestimmt.'),('Übergabe und Kontinuität','Standards und offene Aufgaben werden dokumentiert. Die spätere Führung soll auf nachvollziehbaren Strukturen aufbauen können.')],
'Nach einem Führungswechsel fehlt die Abstimmung zwischen Küche, Service und Veranstaltungsverkauf. Ein befristeter Einsatz ordnet Besprechungen, Zuständigkeiten und Übergaben, während die dauerhafte Nachfolge aufgebaut wird.',
['Klarer Einsatzauftrag und Zuständigkeiten','Priorisierte operative Maßnahmen','Regelmäßige Abstimmung mit der Geschäftsführung','Dokumentierte Übergabe an die Folgeorganisation'],
[('Sind Sie dauerhaft vor Ort?','Präsenz und Umfang werden abhängig vom Auftrag und meiner Verfügbarkeit vereinbart. Ein Interim-Einsatz wird vorab zeitlich und organisatorisch abgestimmt.'),('Ist das auch für ein einzelnes Restaurant möglich?','Ja. Der Auftrag kann sich auf einen Betrieb oder ein bestimmtes Outlet beziehen. Wichtig sind eine klare Aufgabe und die nötigen Entscheidungswege.')],
['fb-beratung','personal-recruiting','revenue-controlling'])

add('revenue-controlling','Revenue Management & F&B-Controlling','F&B & Hospitality',
'Zahlen verstehen und daraus Entscheidungen machen. Ich unterstütze Budget, Forecast und Ergebnissteuerung mit Blick auf den operativen Alltag.',
'Hoher Umsatz ist kein ausreichendes Zeichen für ein gutes Ergebnis. Personaleinsatz, Wareneinsatz, Auslastung und Produktmix müssen gemeinsam betrachtet werden. Unterschiedliche Datenquellen und uneinheitliche Berichte erschweren oft den Blick darauf, wo sich eine Veränderung tatsächlich lohnt.',
'Wir klären die verfügbaren Daten und die Entscheidungen, die daraus entstehen sollen. Kennzahlen erhalten eindeutige Definitionen und einen passenden Berichtszeitraum. Abweichungen werden mit dem Betrieb eingeordnet; daraus folgen konkrete Maßnahmen statt zusätzlicher Tabellen ohne Verantwortliche.',
[('Budget und Forecast','Planannahmen werden mit Saison, Kapazität und Angebot verbunden. Neue Informationen fließen in einen nachvollziehbaren Forecast ein.'),('Kennzahlen und Berichte','Umsatz je Outlet, Personaleinsatz, Wareneinsatz und Deckungsbeiträge werden passend zum Betrieb strukturiert. Datenqualität und Bezugsgrößen bleiben sichtbar.'),('Preis und Kapazität','Preisgestaltung und verfügbare Leistung werden gemeinsam bewertet. Ein Angebot muss nicht nur Nachfrage schaffen, sondern auch mit Küche, Service und Kapazität umsetzbar sein.')],
'Ein Bankett erzielt hohen Umsatz, bindet aber mehr Personal als geplant. Eine Auswertung von Erlös, Wareneinsatz und Einsatzstunden zeigt, wie künftige Angebote und Personaleinteilung angepasst werden können.',
['Definition relevanter Kennzahlen','Struktur für Budget und Forecast','Nutzbare regelmäßige Berichte','Maßnahmen mit Zuständigkeit und Kontrolltermin'],
[('Reichen unsere Kassendaten aus?','Sie sind oft ein guter Einstieg. Ob zusätzliche Angaben benötigt werden, hängt von der Fragestellung ab; Datenlücken werden bei der Analyse ausdrücklich benannt.'),('Wird alles automatisch ausgewertet?','Erst wenn Daten und Definitionen verlässlich sind, lohnt eine automatische Auswertung. Die Interpretation wichtiger Abweichungen bleibt eine gemeinsame betriebliche Aufgabe.')],
['wareneinsatz-kalkulation','softwareentwicklung','digitalisierung'])

add('personal-recruiting','Hospitality-Recruiting & Teamentwicklung','F&B & Hospitality',
'Passende Menschen finden, gut einarbeiten und gemeinsam führen. Mit Rollen und Standards, die zur Realität von Hotellerie und Gastronomie passen.',
'Eine offene Stelle ist selten nur eine fehlende Person. Unklare Rollen, fehlende Einarbeitung oder ein nicht planbarer Alltag erschweren die Besetzung und Bindung. Erfolgreicher Teamaufbau beginnt deshalb mit einem ehrlichen Blick auf Aufgaben, Führung und die Arbeitsbedingungen im Betrieb.',
'Ich unterstütze die Definition von Rollen, die Vorbereitung des Auswahlverfahrens und die Struktur der Einarbeitung. Gemeinsam entwickeln wir verständliche Standards und geeignete Schulungsformate. Die operative Perspektive hilft, Anforderungen konkret zu formulieren und neue Mitarbeitende schneller ins Team einzubinden.',
[('Rollen und Auswahl','Aufgaben, Verantwortung und Schnittstellen werden beschrieben. Gespräche und praktische Fragen orientieren sich an den tatsächlichen Anforderungen der Position.'),('Onboarding und Ausbildung','Ein planbarer Einstieg verbindet Ansprechpartner, Lernschritte und Rückmeldungen. Serviceabläufe und wichtige Hausstandards werden verständlich vermittelt.'),('Führung und Bindung','Regelmäßige Abstimmung, klarer Dienstplanprozess und erkennbare Entwicklungsmöglichkeiten unterstützen die Zusammenarbeit. Maßnahmen werden an den jeweiligen Betrieb angepasst.')],
'Eine neue Restaurantleitung erhält einen strukturierten Einstieg: Hausstandards, Kalkulationsgrundlagen, Ansprechpartner und konkrete Ziele. Das Team weiß, welche Entscheidungen die neue Rolle übernimmt und wo Abstimmung nötig ist.',
['Rollenprofile und Anforderungsgrundlage','Strukturierter Auswahl- und Einarbeitungsablauf','Passende Schulungsschwerpunkte','Verantwortlichkeiten und regelmäßige Rückmeldung'],
[('Garantieren Sie die Besetzung einer Stelle?','Nein. Die Unterstützung verbessert Profil, Ansprache und Auswahlprozess; eine konkrete Besetzung hängt auch von Markt, Bedingungen und Kandidaten ab.'),('Können bestehende Teams begleitet werden?','Ja. Schulungen, Rollenklärung und Führungsabläufe können unabhängig von einer Neueinstellung vereinbart werden.')],
['interim-fb-management','fb-beratung','werdegang'])

LOOKUP={s['slug']:s for s in SERVICES}
EXISTING={'ki-automatisierung':'AI Automation as a Service','teamo-ki':'TeamO · digitaler KI-Mitarbeiter','fb-beratung':'F&B-Beratung','online-marketing':'Online-Marketing & Digitalstrategie','rechner':'Potenzialrechner','wissen-getraenkevertrag':'Wissen: Getränkeverträge','werdegang':'Mein Werdegang'}

def link(slug):
    title=LOOKUP[slug]['title'] if slug in LOOKUP else EXISTING[slug]
    return f'<a href="{slug}.html">{html.escape(title)} <span aria-hidden="true">↗</span></a>'

def catalogue():
    groups=[('Technologie',['ki-automatisierung','ki-entwicklung','teamo-ki','digitalisierung','softwareentwicklung','app-entwicklung','cybersecurity']),('F&B & Hospitality',['fb-beratung','lieferantenvereinbarungen','getraenkevertraege','rueckverguetungen','wareneinsatz-kalkulation','inventur-warenwirtschaft','interim-fb-management','revenue-controlling','personal-recruiting']),('Digitaler Auftritt',['online-marketing','webdesign','suchmaschinenoptimierung','domain-hosting-email','social-media','foto-video'])]
    return '<div class="portfolio-groups">'+''.join(f'<section><p class="tag">0{i+1} / {label}</p><h3>{["Intelligente Systeme.","Starke Betriebe.","Sichtbare Persönlichkeit."][i]}</h3><div class="portfolio-links">'+''.join(link(slug) for slug in slugs)+'</div></section>' for i,(label,slugs) in enumerate(groups))+'</div>'

def page(s):
    path=s['slug']+'.html'; title=html.escape(s['title']); desc=html.escape(s['lead'])
    modules=''.join(f'<article><span class="tag">0{i+1}</span><h3>{t}</h3><p>{b}</p></article>' for i,(t,b) in enumerate(s['modules']))
    faq=''.join(f'<details><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>' for q,a in s['faq'])
    related=''.join(link(slug) for slug in s['related'])
    schema=json.dumps({'@context':'https://schema.org','@type':'Service','name':s['title'],'description':s['lead'],'url':'https://tafolli.net/'+path,'provider':{'@type':'Person','name':'Kastriot Tafolli','url':'https://tafolli.net/'}},ensure_ascii=False).replace('<','\\u003c')
    crumbs=json.dumps({'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Startseite','item':'https://tafolli.net/'},{'@type':'ListItem','position':2,'name':'Leistungen','item':'https://tafolli.net/leistungen.html'},{'@type':'ListItem','position':3,'name':s['title'],'item':'https://tafolli.net/'+path}]},ensure_ascii=False)
    content=f'''<section class="service-hero"><div class="shell"><nav class="service-breadcrumb" aria-label="Brotkrumennavigation"><a href="index.html">Startseite</a><span>/</span><a href="leistungen.html">Leistungen</a><span>/</span><span>{title}</span></nav><div class="service-hero-grid"><div><p class="tag">{s['group']} / KASTRIOT TAFOLLI</p><h1>{title}</h1><p class="lede">{s['lead']}</p><a href="kontakt.html" class="btn btn-1">Projekt besprechen ↗</a></div><div class="service-visual" aria-hidden="true"><span class="tag">PRAXIS × TECHNOLOGIE</span><span class="service-symbol">✳</span><div><span>VERSTEHEN</span><span>VERBINDEN</span><span>UMSETZEN</span></div></div></div><nav class="service-toc" aria-label="Auf dieser Seite"><a href="#ausgangslage">01 Ausgangslage</a><a href="#umfang">02 Leistungen</a><a href="#praxis">03 Praxis</a><a href="#ergebnisse">04 Zusammenarbeit</a><a href="#fragen">05 Fragen</a></nav></div></section>
<section class="service-section" id="ausgangslage"><div class="shell service-editorial"><div><p class="tag">01 / AUSGANGSLAGE</p><h2>Am Alltag<br>ansetzen.</h2></div><div><p>{s['problem']}</p><p>{s['approach']}</p></div></div></section>
<section class="service-section service-tint" id="umfang"><div class="shell"><p class="tag">02 / WAS DAZUGEHÖRT</p><h2>Konkrete Arbeit.<br>Klare Zuständigkeiten.</h2><div class="service-modules">{modules}</div></div></section>
<section class="service-section" id="praxis"><div class="shell service-editorial"><div><p class="tag">03 / EIN MÖGLICHER ANWENDUNGSFALL</p><h2>So wird es<br>praktisch.</h2></div><div class="service-example"><span aria-hidden="true">↗</span><p>{s['example']}</p><small>Zur Erklärung: ein beispielhafter Ablauf, keine Kundenerfolgsmeldung.</small></div></div></section>
<section class="service-section service-tint" id="ergebnisse"><div class="shell service-editorial"><div><p class="tag">04 / ZUSAMMENARBEIT</p><h2>Was Sie<br>mitnehmen.</h2></div><div><ul class="service-outputs">{''.join('<li>'+t+'</li>' for t in s['outputs'])}</ul><p>Am Anfang steht ein Gespräch über Ihren Betrieb. Danach erhalten Sie ein Angebot mit Umfang, Prioritäten und Zuständigkeiten. Wir beginnen mit einem überschaubaren Auftrag und prüfen gemeinsam, wie die Ergebnisse in Ihren Alltag passen. Eine laufende Begleitung kann separat vereinbart werden.</p><p>Meine Perspektive verbindet operative Hotellerie und Gastronomie mit Softwareentwicklung und KI. So lassen sich technische Möglichkeiten und die Anforderungen von Küche, Service und Führung gemeinsam betrachten.</p></div></div></section>
<section class="service-section" id="fragen"><div class="shell service-editorial"><div><p class="tag">05 / HÄUFIGE FRAGEN</p><h2>Gut zu<br>wissen.</h2></div><div class="service-faq">{faq}</div></div></section>
<section class="service-section service-related"><div class="shell"><p class="tag">DAS PASST DAZU</p><h2>Weiterdenken.</h2><div class="portfolio-links">{related}</div><a class="lnk" href="leistungen.html">Das gesamte Portfolio ansehen ↗</a></div></section>'''
    content+=cta_block('// nächster schritt',[["Lassen Sie uns"],["konkret werden."]],f'Erzählen Sie mir, was Sie bei {title} verbessern möchten. Gemeinsam klären wir den passenden ersten Schritt.','Gespräch vereinbaren','kontakt.html','Über mich','ueber-mich.html')
    content+=f'<script type="application/ld+json">{schema}</script><script type="application/ld+json">{crumbs}</script>'
    return seite_rahmen('leistungen.html',title+' · Kastriot Tafolli',desc,path,content)

def build(root):
    for s in SERVICES:
        (root/(s['slug']+'.html')).write_text(page(s))
        print('  '+s['slug']+'.html [Leistung]')
